-- PENDING REVIEW — DO NOT APPLY WITHOUT SIGN-OFF.
-- Draft grant hardening for public SECURITY DEFINER functions.
-- Generated by task 9.2 of openspec change go-live-2026-07-11-gate-remediation.
-- Evidence: docs/audits/2026-07-go-live-advisors/definer-function-inventory.{json,md}
--
-- Semantics:
--   * REVOKE ... FROM PUBLIC pins the already-displaced default grant explicitly (idempotent).
--   * anon is revoked ONLY where the inventory shows zero anon call-site evidence.
--   * anon-preserving functions keep anon EXECUTE (public results + RLS helpers; ringside
--     passcode sessions use the authenticated role via anonymous sign-in, not anon).
--   * unconfident functions are intentionally OMITTED pending human disposition (see .md).
--
BEGIN;

-- _account_ringside_show_id: service-only — internal SQL helper invoked from other SECURITY DEFINER bodies (5 in-SQL call sites); direct rpc use only in DB contract tests
REVOKE EXECUTE ON FUNCTION public._account_ringside_show_id(text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public._account_ringside_show_id(text) TO service_role;

-- _can_manage_show_passcodes: service-only — internal authz helper called via IF NOT public._can_manage_show_passcodes(...) inside definer bodies; no client call sites
REVOKE EXECUTE ON FUNCTION public._can_manage_show_passcodes(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public._can_manage_show_passcodes(uuid) TO service_role;

-- _generate_unique_role_code: service-only — internal SQL helper (9 in-SQL call sites); no client call sites
REVOKE EXECUTE ON FUNCTION public._generate_unique_role_code(text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public._generate_unique_role_code(text) TO service_role;

-- _hash_passcode: authenticated
REVOKE EXECUTE ON FUNCTION public._hash_passcode(text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public._hash_passcode(text) TO service_role, authenticated;

-- _random_role_code: service-only — internal SQL helper called from _generate_unique_role_code; no client call sites
REVOKE EXECUTE ON FUNCTION public._random_role_code(text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public._random_role_code(text) TO service_role;

-- approve_role_request: authenticated
REVOKE EXECUTE ON FUNCTION public.approve_role_request(uuid, uuid, uuid, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.approve_role_request(uuid, uuid, uuid, text) TO service_role, authenticated;

-- assign_armband: authenticated
REVOKE EXECUTE ON FUNCTION public.assign_armband(uuid, uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.assign_armband(uuid, uuid) TO service_role, authenticated;

-- audit_cron_vault_secrets: service-only — called only from edge functions running with service-role key
REVOKE EXECUTE ON FUNCTION public.audit_cron_vault_secrets() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.audit_cron_vault_secrets() TO service_role;

-- can_manage_show: authenticated — RLS policy predicate / helper; needs EXECUTE for authenticated policy evaluation
REVOKE EXECUTE ON FUNCTION public.can_manage_show(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.can_manage_show(uuid) TO service_role, authenticated;

-- can_manage_show_dog: authenticated — RLS policy predicate / helper; needs EXECUTE for authenticated policy evaluation
REVOKE EXECUTE ON FUNCTION public.can_manage_show_dog(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.can_manage_show_dog(uuid) TO service_role, authenticated;

-- can_manage_show_lifecycle_email: authenticated — RLS policy predicate / helper; needs EXECUTE for authenticated policy evaluation
REVOKE EXECUTE ON FUNCTION public.can_manage_show_lifecycle_email(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.can_manage_show_lifecycle_email(uuid) TO service_role, authenticated;

-- can_manage_show_person: authenticated — RLS policy predicate / helper; needs EXECUTE for authenticated policy evaluation
REVOKE EXECUTE ON FUNCTION public.can_manage_show_person(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.can_manage_show_person(uuid) TO service_role, authenticated;

-- can_manage_show_person_for_show: service-only — internal authz helper called via IF NOT ... inside delete_show_managed_person definer body (20260605192839_tighten_people_delete_scope.sql); no client call sites
REVOKE EXECUTE ON FUNCTION public.can_manage_show_person_for_show(uuid, uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.can_manage_show_person_for_show(uuid, uuid) TO service_role;

-- can_manage_trial: authenticated — RLS policy predicate / helper; needs EXECUTE for authenticated policy evaluation
REVOKE EXECUTE ON FUNCTION public.can_manage_trial(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.can_manage_trial(uuid) TO service_role, authenticated;

-- cart_item_identity_change_sever_session: service-only — trigger-target: executes as table owner; no client EXECUTE needed
REVOKE EXECUTE ON FUNCTION public.cart_item_identity_change_sever_session() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.cart_item_identity_change_sever_session() TO service_role;

-- check_and_record_premium_generation_attempt: service-only — called only from edge functions running with service-role key
REVOKE EXECUTE ON FUNCTION public.check_and_record_premium_generation_attempt(uuid, uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.check_and_record_premium_generation_attempt(uuid, uuid) TO service_role;

-- check_class_availability: authenticated
REVOKE EXECUTE ON FUNCTION public.check_class_availability(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.check_class_availability(uuid) TO service_role, authenticated;

-- check_login_rate_limit: service-only — called only from edge functions running with service-role key
REVOKE EXECUTE ON FUNCTION public.check_login_rate_limit(text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.check_login_rate_limit(text) TO service_role;

-- cleanup_stale_ringside_anon_users: authenticated — migration contains explicit GRANT EXECUTE TO authenticated (deliberate client RPC surface)
REVOKE EXECUTE ON FUNCTION public.cleanup_stale_ringside_anon_users(interval, interval, interval) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.cleanup_stale_ringside_anon_users(interval, interval, interval) TO service_role, authenticated;

-- clear_ringside_session_presence: authenticated
REVOKE EXECUTE ON FUNCTION public.clear_ringside_session_presence(text, uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.clear_ringside_session_presence(text, uuid) TO service_role, authenticated;

-- create_dog_with_registrations: authenticated
REVOKE EXECUTE ON FUNCTION public.create_dog_with_registrations(jsonb, jsonb) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.create_dog_with_registrations(jsonb, jsonb) TO service_role, authenticated;

-- create_online_paid_entry: service-only — called only from edge functions running with service-role key
REVOKE EXECUTE ON FUNCTION public.create_online_paid_entry(uuid, uuid, uuid, numeric, text, text, text, timestamp with time zone, uuid, uuid, uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.create_online_paid_entry(uuid, uuid, uuid, numeric, text, text, text, timestamp with time zone, uuid, uuid, uuid) TO service_role;

-- create_or_reuse_club: authenticated
REVOKE EXECUTE ON FUNCTION public.create_or_reuse_club(jsonb) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.create_or_reuse_club(jsonb) TO service_role, authenticated;

-- create_show_managed_dog: authenticated — migration contains explicit GRANT EXECUTE TO authenticated (deliberate client RPC surface)
REVOKE EXECUTE ON FUNCTION public.create_show_managed_dog(uuid, uuid, text, text, text, text, text, text, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.create_show_managed_dog(uuid, uuid, text, text, text, text, text, text, text) TO service_role, authenticated;

-- create_show_managed_person: authenticated — migration contains explicit GRANT EXECUTE TO authenticated (deliberate client RPC surface)
REVOKE EXECUTE ON FUNCTION public.create_show_managed_person(uuid, text, text, text, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.create_show_managed_person(uuid, text, text, text, text) TO service_role, authenticated;

-- create_show_with_children: authenticated
REVOKE EXECUTE ON FUNCTION public.create_show_with_children(jsonb, jsonb, jsonb, uuid[]) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.create_show_with_children(jsonb, jsonb, jsonb, uuid[]) TO service_role, authenticated;

-- delete_show_managed_person: authenticated — migration contains explicit GRANT EXECUTE TO authenticated (deliberate client RPC surface)
REVOKE EXECUTE ON FUNCTION public.delete_show_managed_person(uuid, uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.delete_show_managed_person(uuid, uuid) TO service_role, authenticated;

-- deny_role_request: authenticated
REVOKE EXECUTE ON FUNCTION public.deny_role_request(uuid, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.deny_role_request(uuid, text) TO service_role, authenticated;

-- ensure_show_lifecycle_email_steps: service-only — invoked via PERFORM from ensure_show_lifecycle_email_steps_for_new_show trigger wrapper; live authenticated grant is unused surface — flagged for review
REVOKE EXECUTE ON FUNCTION public.ensure_show_lifecycle_email_steps(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.ensure_show_lifecycle_email_steps(uuid) TO service_role;

-- ensure_show_lifecycle_email_steps_for_new_show: service-only — trigger-target: executes as table owner; no client EXECUTE needed
REVOKE EXECUTE ON FUNCTION public.ensure_show_lifecycle_email_steps_for_new_show() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.ensure_show_lifecycle_email_steps_for_new_show() TO service_role;

-- entries_protect_payment_fields: service-only — trigger-target: executes as table owner; no client EXECUTE needed
REVOKE EXECUTE ON FUNCTION public.entries_protect_payment_fields() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.entries_protect_payment_fields() TO service_role;

-- entries_protect_payment_fields_insert: service-only — trigger-target: executes as table owner; no client EXECUTE needed
REVOKE EXECUTE ON FUNCTION public.entries_protect_payment_fields_insert() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.entries_protect_payment_fields_insert() TO service_role;

-- entries_protect_payment_status: service-only — trigger-target: executes as table owner; no client EXECUTE needed
REVOKE EXECUTE ON FUNCTION public.entries_protect_payment_status() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.entries_protect_payment_status() TO service_role;

-- entry_cart_items_protect_cart_id: service-only — trigger-target: executes as table owner; no client EXECUTE needed
REVOKE EXECUTE ON FUNCTION public.entry_cart_items_protect_cart_id() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.entry_cart_items_protect_cart_id() TO service_role;

-- entry_carts_protect_session_id: service-only — trigger-target: executes as table owner; no client EXECUTE needed
REVOKE EXECUTE ON FUNCTION public.entry_carts_protect_session_id() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.entry_carts_protect_session_id() TO service_role;

-- entry_carts_protect_status: service-only — trigger-target: executes as table owner; no client EXECUTE needed
REVOKE EXECUTE ON FUNCTION public.entry_carts_protect_status() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.entry_carts_protect_status() TO service_role;

-- evaluate_entry_capacity: service-only — migration grants EXECUTE to service roles only; live client grant (if any) is drift — flagged for review
REVOKE EXECUTE ON FUNCTION public.evaluate_entry_capacity(uuid, uuid, uuid, uuid, text, boolean) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.evaluate_entry_capacity(uuid, uuid, uuid, uuid, text, boolean) TO service_role;

-- get_account_today_entries: authenticated
REVOKE EXECUTE ON FUNCTION public.get_account_today_entries() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_account_today_entries() TO service_role, authenticated;

-- get_admin_user_list: authenticated
REVOKE EXECUTE ON FUNCTION public.get_admin_user_list(boolean) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_admin_user_list(boolean) TO service_role, authenticated;

-- get_club_show_manager_ids: authenticated
REVOKE EXECUTE ON FUNCTION public.get_club_show_manager_ids(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_club_show_manager_ids(uuid) TO service_role, authenticated;

-- get_deleted_classes: authenticated
REVOKE EXECUTE ON FUNCTION public.get_deleted_classes() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_deleted_classes() TO service_role, authenticated;

-- get_deleted_dogs: authenticated
REVOKE EXECUTE ON FUNCTION public.get_deleted_dogs() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_deleted_dogs() TO service_role, authenticated;

-- get_deleted_people: authenticated
REVOKE EXECUTE ON FUNCTION public.get_deleted_people() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_deleted_people() TO service_role, authenticated;

-- get_deleted_shows: authenticated
REVOKE EXECUTE ON FUNCTION public.get_deleted_shows() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_deleted_shows() TO service_role, authenticated;

-- get_effective_permissions: authenticated
REVOKE EXECUTE ON FUNCTION public.get_effective_permissions(uuid, text, uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_effective_permissions(uuid, text, uuid) TO service_role, authenticated;

-- get_entries_for_export: authenticated
REVOKE EXECUTE ON FUNCTION public.get_entries_for_export(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_entries_for_export(uuid) TO service_role, authenticated;

-- get_judge_day_capacity: authenticated — migration contains explicit GRANT EXECUTE TO authenticated (deliberate client RPC surface)
REVOKE EXECUTE ON FUNCTION public.get_judge_day_capacity(uuid, uuid, date) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_judge_day_capacity(uuid, uuid, date) TO service_role, authenticated;

-- get_judge_day_capacity_live: service-only — migration grants EXECUTE to service roles only; live client grant (if any) is drift — flagged for review
REVOKE EXECUTE ON FUNCTION public.get_judge_day_capacity_live(uuid, uuid, date) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_judge_day_capacity_live(uuid, uuid, date) TO service_role;

-- get_my_handled_dog_ids: authenticated — RLS policy predicate / helper; needs EXECUTE for authenticated policy evaluation
REVOKE EXECUTE ON FUNCTION public.get_my_handled_dog_ids() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_my_handled_dog_ids() TO service_role, authenticated;

-- get_my_person_id: anon-preserving — RLS policy predicate evaluated under querying role; anon-readable tables reference it; NOTE: ringside passcode sessions use Supabase anonymous sign-in (JWT role = authenticated); true anon here serves public/unauthenticated reads
REVOKE EXECUTE ON FUNCTION public.get_my_person_id() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_my_person_id() TO service_role, authenticated, anon;

-- get_show_officials: authenticated
REVOKE EXECUTE ON FUNCTION public.get_show_officials(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_show_officials(uuid) TO service_role, authenticated;

-- get_user_permissions: authenticated
REVOKE EXECUTE ON FUNCTION public.get_user_permissions(uuid, text, uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_user_permissions(uuid, text, uuid) TO service_role, authenticated;

-- get_user_roles: authenticated
REVOKE EXECUTE ON FUNCTION public.get_user_roles(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_user_roles(uuid) TO service_role, authenticated;

-- grant_club_admin_to_club_creator: service-only — trigger-target: executes as table owner; no client EXECUTE needed
REVOKE EXECUTE ON FUNCTION public.grant_club_admin_to_club_creator() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.grant_club_admin_to_club_creator() TO service_role;

-- grant_club_secretary: authenticated — migration contains explicit GRANT EXECUTE TO authenticated (deliberate client RPC surface)
REVOKE EXECUTE ON FUNCTION public.grant_club_secretary(uuid, uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.grant_club_secretary(uuid, uuid) TO service_role, authenticated;

-- grant_show_official: authenticated
REVOKE EXECUTE ON FUNCTION public.grant_show_official(uuid, text, uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.grant_show_official(uuid, text, uuid) TO service_role, authenticated;

-- guard_platform_settings_write: service-only — trigger-target: executes as table owner; no client EXECUTE needed
REVOKE EXECUTE ON FUNCTION public.guard_platform_settings_write() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.guard_platform_settings_write() TO service_role;

-- handle_entry_scoring_state_change: service-only — trigger-target: executes as table owner; no client EXECUTE needed
REVOKE EXECUTE ON FUNCTION public.handle_entry_scoring_state_change() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.handle_entry_scoring_state_change() TO service_role;

-- handle_new_user: service-only — trigger-target: executes as table owner; no client EXECUTE needed
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.handle_new_user() TO service_role;

-- hard_delete_show: authenticated
REVOKE EXECUTE ON FUNCTION public.hard_delete_show(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.hard_delete_show(uuid) TO service_role, authenticated;

-- has_role: anon-preserving — RLS policy predicate evaluated under querying role; anon-readable tables reference it; NOTE: ringside passcode sessions use Supabase anonymous sign-in (JWT role = authenticated); true anon here serves public/unauthenticated reads
REVOKE EXECUTE ON FUNCTION public.has_role(text, uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.has_role(text, uuid) TO service_role, authenticated, anon;

-- increment_promo_usage: authenticated
REVOKE EXECUTE ON FUNCTION public.increment_promo_usage(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.increment_promo_usage(uuid) TO service_role, authenticated;

-- insert_club_access_request_from_signup: authenticated — supabase_auth_admin grant preserved (auth hook / signup materialization path)
REVOKE EXECUTE ON FUNCTION public.insert_club_access_request_from_signup(uuid, uuid, jsonb) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.insert_club_access_request_from_signup(uuid, uuid, jsonb) TO service_role, supabase_auth_admin, authenticated;

-- insert_show_passcodes: authenticated
REVOKE EXECUTE ON FUNCTION public.insert_show_passcodes(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.insert_show_passcodes(uuid) TO service_role, authenticated;

-- insert_signup_role_requests: service-only — migration grants EXECUTE to service roles only; live client grant (if any) is drift — flagged for review
REVOKE EXECUTE ON FUNCTION public.insert_signup_role_requests(uuid, uuid, jsonb) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.insert_signup_role_requests(uuid, uuid, jsonb) TO service_role;

-- is_club_admin: anon-preserving — anon EXECUTE preserved: live anon grant + client call site (public results / RLS-adjacent read path); NOTE: ringside passcode sessions use Supabase anonymous sign-in (JWT role = authenticated); true anon here serves public/unauthenticated reads
REVOKE EXECUTE ON FUNCTION public.is_club_admin(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.is_club_admin(uuid) TO service_role, authenticated, anon;

-- is_platform_admin: anon-preserving — anon EXECUTE preserved: live anon grant + client call site (public results / RLS-adjacent read path); NOTE: ringside passcode sessions use Supabase anonymous sign-in (JWT role = authenticated); true anon here serves public/unauthenticated reads
REVOKE EXECUTE ON FUNCTION public.is_platform_admin() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.is_platform_admin() TO service_role, authenticated, anon;

-- is_show_manager: authenticated — RLS policy predicate / helper; needs EXECUTE for authenticated policy evaluation
REVOKE EXECUTE ON FUNCTION public.is_show_manager() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.is_show_manager() TO service_role, authenticated;

-- is_show_official: anon-preserving — RLS policy predicate evaluated under querying role; anon-readable tables reference it; NOTE: ringside passcode sessions use Supabase anonymous sign-in (JWT role = authenticated); true anon here serves public/unauthenticated reads
REVOKE EXECUTE ON FUNCTION public.is_show_official(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.is_show_official(uuid) TO service_role, authenticated, anon;

-- is_show_secretary: anon-preserving — anon EXECUTE preserved: live anon grant + client call site (public results / RLS-adjacent read path); NOTE: ringside passcode sessions use Supabase anonymous sign-in (JWT role = authenticated); true anon here serves public/unauthenticated reads
REVOKE EXECUTE ON FUNCTION public.is_show_secretary(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.is_show_secretary(uuid) TO service_role, authenticated, anon;

-- is_show_secretary: anon-preserving — anon EXECUTE preserved: live anon grant + client call site (public results / RLS-adjacent read path); NOTE: ringside passcode sessions use Supabase anonymous sign-in (JWT role = authenticated); true anon here serves public/unauthenticated reads
REVOKE EXECUTE ON FUNCTION public.is_show_secretary() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.is_show_secretary() TO service_role, authenticated, anon;

-- is_site_admin: anon-preserving — anon EXECUTE preserved: live anon grant + client call site (public results / RLS-adjacent read path); NOTE: ringside passcode sessions use Supabase anonymous sign-in (JWT role = authenticated); true anon here serves public/unauthenticated reads
REVOKE EXECUTE ON FUNCTION public.is_site_admin() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.is_site_admin() TO service_role, authenticated, anon;

-- is_trial_secretary: anon-preserving — RLS policy predicate evaluated under querying role; anon-readable tables reference it; NOTE: ringside passcode sessions use Supabase anonymous sign-in (JWT role = authenticated); true anon here serves public/unauthenticated reads
REVOKE EXECUTE ON FUNCTION public.is_trial_secretary(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.is_trial_secretary(uuid) TO service_role, authenticated, anon;

-- list_cron_vault_secret_refs: service-only — called only from edge functions running with service-role key
REVOKE EXECUTE ON FUNCTION public.list_cron_vault_secret_refs() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.list_cron_vault_secret_refs() TO service_role;

-- materialize_club_access_request_from_auth_user: service-only — supabase_auth_admin grant preserved (auth hook / signup materialization path); trigger-target: executes as table owner; no client EXECUTE needed
REVOKE EXECUTE ON FUNCTION public.materialize_club_access_request_from_auth_user() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.materialize_club_access_request_from_auth_user() TO service_role, supabase_auth_admin;

-- notify_announcement_push: service-only — trigger-target: executes as table owner; no client EXECUTE needed
REVOKE EXECUTE ON FUNCTION public.notify_announcement_push() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.notify_announcement_push() TO service_role;

-- notify_chat_message: service-only — trigger-target: executes as table owner; no client EXECUTE needed
REVOKE EXECUTE ON FUNCTION public.notify_chat_message() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.notify_chat_message() TO service_role;

-- notify_class_status_push: service-only — trigger-target: executes as table owner; no client EXECUTE needed
REVOKE EXECUTE ON FUNCTION public.notify_class_status_push() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.notify_class_status_push() TO service_role;

-- notify_entry_scoring_push: service-only — trigger-target: executes as table owner; no client EXECUTE needed
REVOKE EXECUTE ON FUNCTION public.notify_entry_scoring_push() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.notify_entry_scoring_push() TO service_role;

-- notify_support_message: service-only — trigger-target: executes as table owner; no client EXECUTE needed
REVOKE EXECUTE ON FUNCTION public.notify_support_message() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.notify_support_message() TO service_role;

-- notify_waitlist_invite: service-only — trigger-target: executes as table owner; no client EXECUTE needed
REVOKE EXECUTE ON FUNCTION public.notify_waitlist_invite() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.notify_waitlist_invite() TO service_role;

-- people_protect_early_adopter: service-only — trigger-target: executes as table owner; no client EXECUTE needed
REVOKE EXECUTE ON FUNCTION public.people_protect_early_adopter() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.people_protect_early_adopter() TO service_role;

-- people_protect_status: service-only — trigger-target: executes as table owner; no client EXECUTE needed
REVOKE EXECUTE ON FUNCTION public.people_protect_status() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.people_protect_status() TO service_role;

-- prevent_orphaning_dogs_on_person_delete: service-only — trigger-target: executes as table owner; no client EXECUTE needed
REVOKE EXECUTE ON FUNCTION public.prevent_orphaning_dogs_on_person_delete() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.prevent_orphaning_dogs_on_person_delete() TO service_role;

-- promote_waitlist_entry: authenticated
REVOKE EXECUTE ON FUNCTION public.promote_waitlist_entry(uuid, integer) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.promote_waitlist_entry(uuid, integer) TO service_role, authenticated;

-- promote_waitlist_entry_from_cron: service-only — called only from edge functions running with service-role key
REVOKE EXECUTE ON FUNCTION public.promote_waitlist_entry_from_cron(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.promote_waitlist_entry_from_cron(uuid) TO service_role;

-- promote_waitlist_entry_internal: service-only — migration grants EXECUTE to service roles only; live client grant (if any) is drift — flagged for review
REVOKE EXECUTE ON FUNCTION public.promote_waitlist_entry_internal(uuid, integer) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.promote_waitlist_entry_internal(uuid, integer) TO service_role;

-- propagate_people_auth_user_id_to_user_roles: service-only — trigger-target: executes as table owner; no client EXECUTE needed
REVOKE EXECUTE ON FUNCTION public.propagate_people_auth_user_id_to_user_roles() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.propagate_people_auth_user_id_to_user_roles() TO service_role;

-- prune_premium_generation_attempts: service-only — migration grants EXECUTE to service roles only; live client grant (if any) is drift — flagged for review
REVOKE EXECUTE ON FUNCTION public.prune_premium_generation_attempts() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.prune_premium_generation_attempts() TO service_role;

-- prune_stale_ringside_sessions: service-only — migration grants EXECUTE to service roles only; live client grant (if any) is drift — flagged for review
REVOKE EXECUTE ON FUNCTION public.prune_stale_ringside_sessions() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.prune_stale_ringside_sessions() TO service_role;

-- recalculate_class_placements: service-only — migration grants EXECUTE to service roles only; live client grant (if any) is drift — flagged for review
REVOKE EXECUTE ON FUNCTION public.recalculate_class_placements(uuid[], boolean) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.recalculate_class_placements(uuid[], boolean) TO service_role;

-- record_login_attempt: service-only — called only from edge functions running with service-role key
REVOKE EXECUTE ON FUNCTION public.record_login_attempt(text, boolean, text, uuid, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.record_login_attempt(text, boolean, text, uuid, text) TO service_role;

-- refresh_class_scoring_state: service-only — called only from edge functions running with service-role key
REVOKE EXECUTE ON FUNCTION public.refresh_class_scoring_state(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.refresh_class_scoring_state(uuid) TO service_role;

-- refresh_class_scoring_state_authorized: authenticated
REVOKE EXECUTE ON FUNCTION public.refresh_class_scoring_state_authorized(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.refresh_class_scoring_state_authorized(uuid) TO service_role, authenticated;

-- regenerate_show_passcodes: authenticated
REVOKE EXECUTE ON FUNCTION public.regenerate_show_passcodes(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.regenerate_show_passcodes(uuid) TO service_role, authenticated;

-- resolve_class_result_visibility: anon-preserving — consumed via CROSS JOIN LATERAL inside view_public_entry_results / view_authenticated_entry_results (task 9.3); anon EXECUTE preserved for public results reads; NOTE: ringside passcode sessions use Supabase anonymous sign-in (JWT role = authenticated); true anon here serves public/unauthenticated reads
REVOKE EXECUTE ON FUNCTION public.resolve_class_result_visibility(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.resolve_class_result_visibility(uuid) TO service_role, authenticated, anon;

-- resolve_operator_alert: authenticated
REVOKE EXECUTE ON FUNCTION public.resolve_operator_alert(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.resolve_operator_alert(uuid) TO service_role, authenticated;

-- restore_class: authenticated
REVOKE EXECUTE ON FUNCTION public.restore_class(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.restore_class(uuid) TO service_role, authenticated;

-- restore_dog: authenticated
REVOKE EXECUTE ON FUNCTION public.restore_dog(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.restore_dog(uuid) TO service_role, authenticated;

-- restore_person: authenticated
REVOKE EXECUTE ON FUNCTION public.restore_person(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.restore_person(uuid) TO service_role, authenticated;

-- restore_show: authenticated
REVOKE EXECUTE ON FUNCTION public.restore_show(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.restore_show(uuid) TO service_role, authenticated;

-- restrict_entry_refund_columns: service-only — trigger-target: executes as table owner; no client EXECUTE needed
REVOKE EXECUTE ON FUNCTION public.restrict_entry_refund_columns() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.restrict_entry_refund_columns() TO service_role;

-- restrict_payment_status_update: service-only — trigger-target: executes as table owner; no client EXECUTE needed
REVOKE EXECUTE ON FUNCTION public.restrict_payment_status_update() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.restrict_payment_status_update() TO service_role;

-- restrict_subscription_column_updates: service-only — trigger-target: executes as table owner; no client EXECUTE needed
REVOKE EXECUTE ON FUNCTION public.restrict_subscription_column_updates() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.restrict_subscription_column_updates() TO service_role;

-- restrict_support_ticket_update_columns: service-only — trigger-target: executes as table owner; no client EXECUTE needed
REVOKE EXECUTE ON FUNCTION public.restrict_support_ticket_update_columns() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.restrict_support_ticket_update_columns() TO service_role;

-- review_club_access_request: authenticated — migration contains explicit GRANT EXECUTE TO authenticated (deliberate client RPC surface)
REVOKE EXECUTE ON FUNCTION public.review_club_access_request(uuid, text, uuid, text, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.review_club_access_request(uuid, text, uuid, text, text) TO service_role, authenticated;

-- revoke_club_secretary: authenticated — migration contains explicit GRANT EXECUTE TO authenticated (deliberate client RPC surface)
REVOKE EXECUTE ON FUNCTION public.revoke_club_secretary(uuid, uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.revoke_club_secretary(uuid, uuid) TO service_role, authenticated;

-- ringside_claim_generation_current: authenticated
REVOKE EXECUTE ON FUNCTION public.ringside_claim_generation_current() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.ringside_claim_generation_current() TO service_role, authenticated;

-- ringside_update_entry: authenticated
REVOKE EXECUTE ON FUNCTION public.ringside_update_entry(uuid, jsonb, integer) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.ringside_update_entry(uuid, jsonb, integer) TO service_role, authenticated;

-- self_checkin_entry: authenticated
REVOKE EXECUTE ON FUNCTION public.self_checkin_entry(uuid, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.self_checkin_entry(uuid, text) TO service_role, authenticated;

-- soft_delete_class: authenticated
REVOKE EXECUTE ON FUNCTION public.soft_delete_class(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.soft_delete_class(uuid) TO service_role, authenticated;

-- soft_delete_dog: authenticated
REVOKE EXECUTE ON FUNCTION public.soft_delete_dog(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.soft_delete_dog(uuid) TO service_role, authenticated;

-- soft_delete_person: authenticated
REVOKE EXECUTE ON FUNCTION public.soft_delete_person(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.soft_delete_person(uuid) TO service_role, authenticated;

-- soft_delete_show: authenticated
REVOKE EXECUTE ON FUNCTION public.soft_delete_show(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.soft_delete_show(uuid) TO service_role, authenticated;

-- stamp_entry_withdrawn_at: service-only — trigger-target: executes as table owner; no client EXECUTE needed
REVOKE EXECUTE ON FUNCTION public.stamp_entry_withdrawn_at() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.stamp_entry_withdrawn_at() TO service_role;

-- stamp_show_refund_entries: service-only — called only from edge functions running with service-role key
REVOKE EXECUTE ON FUNCTION public.stamp_show_refund_entries(uuid[], text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.stamp_show_refund_entries(uuid[], text) TO service_role;

-- submit_club_access_request: authenticated — migration contains explicit GRANT EXECUTE TO authenticated (deliberate client RPC surface)
REVOKE EXECUTE ON FUNCTION public.submit_club_access_request(text, text, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.submit_club_access_request(text, text, text) TO service_role, authenticated;

-- submit_role_request: authenticated — migration contains explicit GRANT EXECUTE TO authenticated (deliberate client RPC surface)
REVOKE EXECUTE ON FUNCTION public.submit_role_request(text, text, uuid, uuid, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.submit_role_request(text, text, uuid, uuid, text) TO service_role, authenticated;

-- submit_show_entries: authenticated
REVOKE EXECUTE ON FUNCTION public.submit_show_entries(uuid, uuid, jsonb, uuid, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.submit_show_entries(uuid, uuid, jsonb, uuid, text) TO service_role, authenticated;

-- sync_dog_registration_deleted_marker: service-only — trigger-target: executes as table owner; no client EXECUTE needed
REVOKE EXECUTE ON FUNCTION public.sync_dog_registration_deleted_marker() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.sync_dog_registration_deleted_marker() TO service_role;

-- sync_dog_registration_deleted_markers_for_dog: service-only — trigger-target: executes as table owner; no client EXECUTE needed
REVOKE EXECUTE ON FUNCTION public.sync_dog_registration_deleted_markers_for_dog() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.sync_dog_registration_deleted_markers_for_dog() TO service_role;

-- sync_enrollment_on_payment_success: service-only — trigger-target: executes as table owner; no client EXECUTE needed
REVOKE EXECUTE ON FUNCTION public.sync_enrollment_on_payment_success() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.sync_enrollment_on_payment_success() TO service_role;

-- sync_user_roles_auth_user_id: service-only — trigger-target: executes as table owner; no client EXECUTE needed
REVOKE EXECUTE ON FUNCTION public.sync_user_roles_auth_user_id() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.sync_user_roles_auth_user_id() TO service_role;

-- system_health_probe: authenticated
REVOKE EXECUTE ON FUNCTION public.system_health_probe() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.system_health_probe() TO service_role, authenticated;

-- test_as_anon: service-only — migration grants EXECUTE to service roles only; live client grant (if any) is drift — flagged for review
REVOKE EXECUTE ON FUNCTION public.test_as_anon() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.test_as_anon() TO service_role;

-- test_as_user: service-only — migration grants EXECUTE to service roles only; live client grant (if any) is drift — flagged for review
REVOKE EXECUTE ON FUNCTION public.test_as_user(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.test_as_user(uuid) TO service_role;

-- test_reset: service-only — migration grants EXECUTE to service roles only; live client grant (if any) is drift — flagged for review
REVOKE EXECUTE ON FUNCTION public.test_reset() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.test_reset() TO service_role;

-- update_entry_handler: authenticated — migration contains explicit GRANT EXECUTE TO authenticated (deliberate client RPC surface)
REVOKE EXECUTE ON FUNCTION public.update_entry_handler(uuid, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.update_entry_handler(uuid, text) TO service_role, authenticated;

-- update_entry_handler_for_entry_management: authenticated
REVOKE EXECUTE ON FUNCTION public.update_entry_handler_for_entry_management(uuid, text, uuid, boolean) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.update_entry_handler_for_entry_management(uuid, text, uuid, boolean) TO service_role, authenticated;

-- update_thread_last_message_at: service-only — trigger-target: executes as table owner; no client EXECUTE needed
REVOKE EXECUTE ON FUNCTION public.update_thread_last_message_at() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.update_thread_last_message_at() TO service_role;

-- upsert_ringside_session: authenticated
REVOKE EXECUTE ON FUNCTION public.upsert_ringside_session(text, text, text[], text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.upsert_ringside_session(text, text, text[], text) TO service_role, authenticated;

-- user_has_permission: authenticated
REVOKE EXECUTE ON FUNCTION public.user_has_permission(uuid, text, text, uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.user_has_permission(uuid, text, text, uuid) TO service_role, authenticated;

-- validate_passcode: authenticated
REVOKE EXECUTE ON FUNCTION public.validate_passcode(text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.validate_passcode(text) TO service_role, authenticated;

-- validate_promo_code: authenticated
REVOKE EXECUTE ON FUNCTION public.validate_promo_code(text, uuid, uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.validate_promo_code(text, uuid, uuid) TO service_role, authenticated;

-- volunteer_show_id: authenticated — RLS policy predicate / helper; needs EXECUTE for authenticated policy evaluation
REVOKE EXECUTE ON FUNCTION public.volunteer_show_id(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.volunteer_show_id(uuid) TO service_role, authenticated;

COMMIT;

-- ---------------------------------------------------------------------------
-- ROLLBACK SQL (manual; restores pre-migration grant surface per live proacl
-- snapshot 2026-07-13 — run inside a transaction):
--
-- GRANT EXECUTE ON FUNCTION public._account_ringside_show_id(text) TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public._can_manage_show_passcodes(uuid) TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public._generate_unique_role_code(text) TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public._hash_passcode(text) TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public._random_role_code(text) TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.approve_role_request(uuid, uuid, uuid, text) TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.assign_armband(uuid, uuid) TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.audit_cron_vault_secrets() TO service_role;
-- GRANT EXECUTE ON FUNCTION public.can_manage_show(uuid) TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.can_manage_show_dog(uuid) TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.can_manage_show_lifecycle_email(uuid) TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.can_manage_show_person(uuid) TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.can_manage_show_person_for_show(uuid, uuid) TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.can_manage_trial(uuid) TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.cart_item_identity_change_sever_session() TO service_role;
-- GRANT EXECUTE ON FUNCTION public.check_and_record_premium_generation_attempt(uuid, uuid) TO service_role;
-- GRANT EXECUTE ON FUNCTION public.check_class_availability(uuid) TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.check_login_rate_limit(text) TO service_role;
-- GRANT EXECUTE ON FUNCTION public.cleanup_stale_ringside_anon_users(interval, interval, interval) TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.clear_ringside_session_presence(text, uuid) TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.create_dog_with_registrations(jsonb, jsonb) TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.create_online_paid_entry(uuid, uuid, uuid, numeric, text, text, text, timestamp with time zone, uuid, uuid, uuid) TO service_role;
-- GRANT EXECUTE ON FUNCTION public.create_or_reuse_club(jsonb) TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.create_show_managed_dog(uuid, uuid, text, text, text, text, text, text, text) TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.create_show_managed_person(uuid, text, text, text, text) TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.create_show_with_children(jsonb, jsonb, jsonb, uuid[]) TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.delete_show_managed_person(uuid, uuid) TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.deny_role_request(uuid, text) TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.ensure_show_lifecycle_email_steps(uuid) TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.ensure_show_lifecycle_email_steps_for_new_show() TO service_role;
-- GRANT EXECUTE ON FUNCTION public.entries_protect_payment_fields() TO service_role;
-- GRANT EXECUTE ON FUNCTION public.entries_protect_payment_fields_insert() TO service_role;
-- GRANT EXECUTE ON FUNCTION public.entries_protect_payment_status() TO service_role;
-- GRANT EXECUTE ON FUNCTION public.entry_cart_items_protect_cart_id() TO service_role;
-- GRANT EXECUTE ON FUNCTION public.entry_carts_protect_session_id() TO service_role;
-- GRANT EXECUTE ON FUNCTION public.entry_carts_protect_status() TO service_role;
-- GRANT EXECUTE ON FUNCTION public.evaluate_entry_capacity(uuid, uuid, uuid, uuid, text, boolean) TO service_role;
-- GRANT EXECUTE ON FUNCTION public.get_account_today_entries() TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.get_admin_user_list(boolean) TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.get_club_show_manager_ids(uuid) TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.get_deleted_classes() TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.get_deleted_dogs() TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.get_deleted_people() TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.get_deleted_shows() TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.get_effective_permissions(uuid, text, uuid) TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.get_entries_for_export(uuid) TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.get_judge_day_capacity(uuid, uuid, date) TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.get_judge_day_capacity_live(uuid, uuid, date) TO service_role;
-- GRANT EXECUTE ON FUNCTION public.get_my_handled_dog_ids() TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.get_my_person_id() TO service_role, authenticated, anon;
-- GRANT EXECUTE ON FUNCTION public.get_show_officials(uuid) TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.get_user_permissions(uuid, text, uuid) TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.get_user_roles(uuid) TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.grant_club_admin_to_club_creator() TO service_role;
-- GRANT EXECUTE ON FUNCTION public.grant_club_secretary(uuid, uuid) TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.grant_show_official(uuid, text, uuid) TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.guard_platform_settings_write() TO service_role;
-- GRANT EXECUTE ON FUNCTION public.handle_entry_scoring_state_change() TO service_role;
-- GRANT EXECUTE ON FUNCTION public.handle_new_user() TO service_role;
-- GRANT EXECUTE ON FUNCTION public.hard_delete_show(uuid) TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.has_role(text, uuid) TO service_role, authenticated, anon;
-- GRANT EXECUTE ON FUNCTION public.increment_promo_usage(uuid) TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.insert_club_access_request_from_signup(uuid, uuid, jsonb) TO service_role, supabase_auth_admin, authenticated;
-- GRANT EXECUTE ON FUNCTION public.insert_show_passcodes(uuid) TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.insert_signup_role_requests(uuid, uuid, jsonb) TO service_role;
-- GRANT EXECUTE ON FUNCTION public.is_club_admin(uuid) TO service_role, authenticated, anon;
-- GRANT EXECUTE ON FUNCTION public.is_platform_admin() TO service_role, authenticated, anon;
-- GRANT EXECUTE ON FUNCTION public.is_show_manager() TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.is_show_official(uuid) TO service_role, authenticated, anon;
-- GRANT EXECUTE ON FUNCTION public.is_show_secretary(uuid) TO service_role, authenticated, anon;
-- GRANT EXECUTE ON FUNCTION public.is_show_secretary() TO service_role, authenticated, anon;
-- GRANT EXECUTE ON FUNCTION public.is_site_admin() TO service_role, authenticated, anon;
-- GRANT EXECUTE ON FUNCTION public.is_trial_secretary(uuid) TO service_role, authenticated, anon;
-- GRANT EXECUTE ON FUNCTION public.list_cron_vault_secret_refs() TO service_role;
-- GRANT EXECUTE ON FUNCTION public.materialize_club_access_request_from_auth_user() TO service_role, supabase_auth_admin;
-- GRANT EXECUTE ON FUNCTION public.notify_announcement_push() TO service_role;
-- GRANT EXECUTE ON FUNCTION public.notify_chat_message() TO service_role;
-- GRANT EXECUTE ON FUNCTION public.notify_class_status_push() TO service_role;
-- GRANT EXECUTE ON FUNCTION public.notify_entry_scoring_push() TO service_role;
-- GRANT EXECUTE ON FUNCTION public.notify_support_message() TO service_role;
-- GRANT EXECUTE ON FUNCTION public.notify_waitlist_invite() TO service_role;
-- GRANT EXECUTE ON FUNCTION public.people_protect_early_adopter() TO service_role;
-- GRANT EXECUTE ON FUNCTION public.people_protect_status() TO service_role;
-- GRANT EXECUTE ON FUNCTION public.prevent_orphaning_dogs_on_person_delete() TO service_role;
-- GRANT EXECUTE ON FUNCTION public.promote_waitlist_entry(uuid, integer) TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.promote_waitlist_entry_from_cron(uuid) TO service_role;
-- GRANT EXECUTE ON FUNCTION public.promote_waitlist_entry_internal(uuid, integer) TO service_role;
-- GRANT EXECUTE ON FUNCTION public.propagate_people_auth_user_id_to_user_roles() TO service_role;
-- GRANT EXECUTE ON FUNCTION public.prune_premium_generation_attempts() TO service_role;
-- GRANT EXECUTE ON FUNCTION public.prune_stale_ringside_sessions() TO service_role;
-- GRANT EXECUTE ON FUNCTION public.recalculate_class_placements(uuid[], boolean) TO service_role;
-- GRANT EXECUTE ON FUNCTION public.record_login_attempt(text, boolean, text, uuid, text) TO service_role;
-- GRANT EXECUTE ON FUNCTION public.refresh_class_scoring_state(uuid) TO service_role;
-- GRANT EXECUTE ON FUNCTION public.refresh_class_scoring_state_authorized(uuid) TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.regenerate_show_passcodes(uuid) TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.resolve_class_result_visibility(uuid) TO service_role, authenticated, anon;
-- GRANT EXECUTE ON FUNCTION public.resolve_operator_alert(uuid) TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.restore_class(uuid) TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.restore_dog(uuid) TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.restore_person(uuid) TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.restore_show(uuid) TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.restrict_entry_refund_columns() TO service_role;
-- GRANT EXECUTE ON FUNCTION public.restrict_payment_status_update() TO service_role;
-- GRANT EXECUTE ON FUNCTION public.restrict_subscription_column_updates() TO service_role;
-- GRANT EXECUTE ON FUNCTION public.restrict_support_ticket_update_columns() TO service_role;
-- GRANT EXECUTE ON FUNCTION public.review_club_access_request(uuid, text, uuid, text, text) TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.revoke_club_secretary(uuid, uuid) TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.ringside_claim_generation_current() TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.ringside_update_entry(uuid, jsonb, integer) TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.self_checkin_entry(uuid, text) TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.soft_delete_class(uuid) TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.soft_delete_dog(uuid) TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.soft_delete_person(uuid) TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.soft_delete_show(uuid) TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.stamp_entry_withdrawn_at() TO service_role;
-- GRANT EXECUTE ON FUNCTION public.stamp_show_refund_entries(uuid[], text) TO service_role;
-- GRANT EXECUTE ON FUNCTION public.submit_club_access_request(text, text, text) TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.submit_role_request(text, text, uuid, uuid, text) TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.submit_show_entries(uuid, uuid, jsonb, uuid, text) TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.sync_dog_registration_deleted_marker() TO service_role;
-- GRANT EXECUTE ON FUNCTION public.sync_dog_registration_deleted_markers_for_dog() TO service_role;
-- GRANT EXECUTE ON FUNCTION public.sync_enrollment_on_payment_success() TO service_role;
-- GRANT EXECUTE ON FUNCTION public.sync_user_roles_auth_user_id() TO service_role;
-- GRANT EXECUTE ON FUNCTION public.system_health_probe() TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.test_as_anon() TO service_role;
-- GRANT EXECUTE ON FUNCTION public.test_as_user(uuid) TO service_role;
-- GRANT EXECUTE ON FUNCTION public.test_reset() TO service_role;
-- GRANT EXECUTE ON FUNCTION public.update_entry_handler(uuid, text) TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.update_entry_handler_for_entry_management(uuid, text, uuid, boolean) TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.update_thread_last_message_at() TO service_role;
-- GRANT EXECUTE ON FUNCTION public.upsert_ringside_session(text, text, text[], text) TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.user_has_permission(uuid, text, text, uuid) TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.validate_passcode(text) TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.validate_promo_code(text, uuid, uuid) TO service_role, authenticated;
-- GRANT EXECUTE ON FUNCTION public.volunteer_show_id(uuid) TO service_role, authenticated;
-- (PUBLIC EXECUTE was already revoked before this migration; do not restore it.)
