export const AKC_SCENT_WORK_ENTRY_FORM_FIELDS = {
  akcCheckbox: 'AKCPALILPCP',
  akcRegisteredName: 'AKCRegisteredName',
  akcRegistrationNumber: 'AKCRegistrionNumber',
  breed: 'Breed',
  breeder: 'Breeder',
  callName: 'CallName',
  city: 'City',
  dam: 'Dam',
  dateOfBirth: 'DOB',
  email: 'Email',
  emailSignature: 'Email2',
  foreignCheckbox: 'Foreign',
  gender: 'Gender',
  handlerName: 'HandlerName',
  ownerAddress: 'OwnerAddress',
  ownerName: 'OwnerName',
  phoneSignature: 'Phone',
  sire: 'Sire',
  signature: 'Signature',
  state: 'State',
  telephone: 'Telephone',
  variety: 'Variety',
  zip: 'Zip',
} as const;

export const AKC_SCENT_WORK_ENTRY_FORM_REQUIRED_FIELDS = [
  AKC_SCENT_WORK_ENTRY_FORM_FIELDS.akcRegisteredName,
  AKC_SCENT_WORK_ENTRY_FORM_FIELDS.akcRegistrationNumber,
  AKC_SCENT_WORK_ENTRY_FORM_FIELDS.callName,
  AKC_SCENT_WORK_ENTRY_FORM_FIELDS.dateOfBirth,
  AKC_SCENT_WORK_ENTRY_FORM_FIELDS.gender,
  AKC_SCENT_WORK_ENTRY_FORM_FIELDS.breed,
  AKC_SCENT_WORK_ENTRY_FORM_FIELDS.ownerName,
  AKC_SCENT_WORK_ENTRY_FORM_FIELDS.ownerAddress,
  AKC_SCENT_WORK_ENTRY_FORM_FIELDS.city,
  AKC_SCENT_WORK_ENTRY_FORM_FIELDS.state,
  AKC_SCENT_WORK_ENTRY_FORM_FIELDS.zip,
  AKC_SCENT_WORK_ENTRY_FORM_FIELDS.telephone,
  AKC_SCENT_WORK_ENTRY_FORM_FIELDS.email,
  AKC_SCENT_WORK_ENTRY_FORM_FIELDS.signature,
] as const;
