export const LIVE_SECRETARY_SHOW_ID =
  process.env.QA_SECRETARY_SHOW_ID ?? 'dededede-0000-0000-0000-000000000010';

export const LIVE_SECRETARY_SHOW_NAME = 'Heartland Scent Work Classic';

export const LIVE_REGISTRATION_SHOW_ID =
  process.env.QA_REGISTRATION_SHOW_ID ?? LIVE_SECRETARY_SHOW_ID;

export const ADD_TRIALS_SHOW_ID = process.env.QA_ADD_TRIALS_SHOW_ID ?? LIVE_SECRETARY_SHOW_ID;
