export const withdrawalPolicyTermFixtures = [
  ['Refunds:\nNone after the closing date.', true],
  ['The club retains the office fee.', true],
  ['50% after the closing date.', true],
  ['$10 office fee applies after closing.', true],
  ['Half the entry fee is returned after closing.', true],
  ['Entry fees are non-refundable after the closing date.', true],
  ['Office fees are retained after closing.', true],
  ['Half of the fee is returned after closing.', true],
  ['Fifty percent of the fee is kept after the closing date.', true],
  ['10 dollars is kept after the closing date.', true],
  ['Entries withdrawn after closing forfeit all fees.', true],
  ['No money back after closing.', true],
  ['Payments are final after the deadline.', true],
  ['Withdrawals are non-refundable.', true],
  ['A 25% administrative charge applies to all withdrawals.', true],
  ['Refunds are not permitted.', true],
  ['Funds are returned before the closing date only.', true],
  ['Withdrawals must be submitted in writing by the closing deadline.', false],
  ['Refunds are processed once the show closes.', false],
  ['We keep exhibitors informed by email.', false],
  ['Move-ups must be requested before the cutoff.', false],
  ['Questions? Email refunds@club.org after the show.', false],
] as const;
