import React from 'react';
import type { ReportProps } from '@/lib/reports/types';
import { isQualified } from '@/lib/reports/reportUtils';

export const JudgesCertification: React.FC<ReportProps> = ({
  showName,
  clubName,
  trial,
  allClasses = [],
  entries,
}) => {
  const judgeName = trial?.judgeName ?? 'Unknown Judge';

  const qualifyingByElement = new Map<string, number>();
  for (const entry of entries) {
    if (isQualified(entry) && entry.classElement) {
      qualifyingByElement.set(
        entry.classElement,
        (qualifyingByElement.get(entry.classElement) ?? 0) + 1
      );
    }
  }

  const elements = [...new Set(allClasses.map(c => c.element))];
  const totalQualifying = [...qualifyingByElement.values()].reduce((sum, n) => sum + n, 0);

  return (
    <div className="report-page">
      <div className="report-header">
        <div className="report-logo">myK9Show</div>
        <h1 className="report-title">Scent Work Judge&apos;s Certification</h1>
        {(clubName ?? showName) && <p className="report-subtitle">{clubName ?? showName}</p>}
        {trial && (
          <p className="report-subtitle">
            {trial.date} · Trial {trial.trialNumber}
          </p>
        )}
      </div>

      <div className="form-section">
        <div className="form-field-row">
          <span className="form-label">Judge&apos;s Name:</span>
          <span className="form-value">{judgeName}</span>
        </div>
      </div>

      <div className="form-section">
        <p>I certify that:</p>
        <table className="report-table">
          <thead>
            <tr>
              <th>Element</th>
              <th>Dogs Receiving Qualifying Scores</th>
            </tr>
          </thead>
          <tbody>
            {elements.map(element => (
              <tr key={element}>
                <td>{element}</td>
                <td>{qualifyingByElement.get(element) ?? 0}</td>
              </tr>
            ))}
            <tr className="total-row">
              <td>
                <strong>Total qualifying in this trial under me</strong>
              </td>
              <td>
                <strong>{totalQualifying}</strong>
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <div className="form-signature-section">
        <div className="signature-line">
          <span className="signature-label">Judge&apos;s Signature:</span>
          <span className="signature-blank" />
        </div>
        <div className="signature-line">
          <span className="signature-label">Date:</span>
          <span className="signature-blank" />
        </div>
      </div>

      <div className="report-footer">
        <div className="footer-right">Generated by myK9Show — Page 1 of 1</div>
      </div>
    </div>
  );
};
