import React from 'react';
import type { ReportProps } from '@/lib/reports/types';
import { formatReportDate } from '@/lib/reports/reportUtils';

const SECONDS_PER_ENTRY = 45;

function formatEstimatedTime(entryCount: number): string {
  const totalSeconds = entryCount * SECONDS_PER_ENTRY;
  const minutes = Math.floor(totalSeconds / 60);
  const seconds = totalSeconds % 60;
  return `${minutes}:${String(seconds).padStart(2, '0')}`;
}

export const JudgesSchedule: React.FC<ReportProps> = ({
  showName,
  organization,
  allTrials = [],
  allClasses = [],
  entries,
  sortOrder,
}) => {
  const entriesPerClass = new Map<string, number>();
  for (const entry of entries) {
    if (entry.classId) {
      entriesPerClass.set(entry.classId, (entriesPerClass.get(entry.classId) ?? 0) + 1);
    }
  }

  const orgTitle = organization ? `${organization} Scent Work` : 'Scent Work';

  function sortClasses(classes: typeof allClasses): typeof allClasses {
    if (sortOrder === 'judge-name') {
      return [...classes].sort((a, b) => (a.judgeName ?? '').localeCompare(b.judgeName ?? ''));
    }
    return classes;
  }

  return (
    <div className="report-page">
      <div className="report-header">
        <div className="report-logo">myK9Show</div>
        <h1 className="report-title">{orgTitle} Show Judging Schedule</h1>
        {showName && <p className="report-subtitle">{showName}</p>}
      </div>

      {allTrials.map(trial => {
        const trialClasses = sortClasses(allClasses.filter(c => c.trialId === trial.id));
        return (
          <div key={trial.id} className="catalog-trial-section">
            <h2 className="catalog-trial-header">
              Trial {trial.trialNumber}
              {trial.date ? ` — ${formatReportDate(trial.date)}` : ''}
            </h2>
            <table className="report-table">
              <thead>
                <tr>
                  <th>Class</th>
                  <th>Judge</th>
                  <th>Entries</th>
                  <th>Est. Time</th>
                </tr>
              </thead>
              <tbody>
                {trialClasses.map(cls => {
                  const count = entriesPerClass.get(cls.id) ?? 0;
                  return (
                    <tr key={cls.id}>
                      <td>{`${cls.element} ${cls.level}`.trim()}</td>
                      <td>{cls.judgeName ?? ''}</td>
                      <td>{count}</td>
                      <td>{formatEstimatedTime(count)}</td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        );
      })}

      <div className="report-footer">
        <div className="footer-left">Est. time = {SECONDS_PER_ENTRY} sec/entry</div>
        <div className="footer-right">Generated by myK9Show</div>
      </div>
    </div>
  );
};
