import React from 'react';
import { useQuery } from '@tanstack/react-query';
import type { ReportProps } from '@/lib/reports/types';
import { trialJudgeSuppliesService } from '@/features/judge-supplies/trialJudgeSuppliesService';
import { judgeKey, type TrialJudgeSupplyRow } from '@/features/judge-supplies/types';
import { formatReportDate } from '@/lib/reports/reportUtils';

interface JudgePage {
  trialId: string;
  trialNumber: string | null;
  trialDate: string | null;
  judgeName: string;
  judgeKey: string;
  rows: TrialJudgeSupplyRow[];
}

function buildPages(
  supplies: TrialJudgeSupplyRow[],
  allTrials: NonNullable<ReportProps['allTrials']>
): JudgePage[] {
  const trialMeta = new Map<string, { trialNumber: string | null; trialDate: string | null }>();
  for (const trial of allTrials) {
    trialMeta.set(trial.id, {
      trialNumber: trial.trialNumber ?? null,
      trialDate: trial.date ?? null,
    });
  }

  const pages = new Map<string, JudgePage>();
  for (const row of supplies) {
    const key = `${row.trial_id}::${judgeKey(row)}`;
    let page = pages.get(key);
    if (!page) {
      const meta = trialMeta.get(row.trial_id) ?? { trialNumber: null, trialDate: null };
      page = {
        trialId: row.trial_id,
        trialNumber: meta.trialNumber,
        trialDate: meta.trialDate,
        judgeName: row.judge_name,
        judgeKey: judgeKey(row),
        rows: [],
      };
      pages.set(key, page);
    }
    page.rows.push(row);
  }

  for (const page of pages.values()) {
    page.rows.sort((a, b) => a.sort_order - b.sort_order);
  }

  return Array.from(pages.values()).sort((a, b) => {
    const dateA = a.trialDate ?? '';
    const dateB = b.trialDate ?? '';
    if (dateA !== dateB) return dateA.localeCompare(dateB);
    const numA = a.trialNumber ?? '';
    const numB = b.trialNumber ?? '';
    if (numA !== numB) return numA.localeCompare(numB);
    return a.judgeName.localeCompare(b.judgeName);
  });
}

export const JudgeSupplyChecklistReport: React.FC<ReportProps> = ({
  showId,
  showName,
  allTrials = [],
}) => {
  const query = useQuery({
    queryKey: ['judge-supply-checklist-report', showId ?? ''] as const,
    queryFn: () => trialJudgeSuppliesService.listForShow(showId!),
    enabled: !!showId,
  });

  if (!showId) {
    return (
      <div className="report-page">
        <p>Show context is required to render judge supply checklists.</p>
      </div>
    );
  }

  if (query.isLoading) {
    return (
      <div className="report-page">
        <p>Loading judge supplies…</p>
      </div>
    );
  }

  if (query.error) {
    return (
      <div className="report-page">
        <p>Could not load judge supplies: {(query.error as Error).message}</p>
      </div>
    );
  }

  const pages = buildPages(query.data ?? [], allTrials);

  if (pages.length === 0) {
    return (
      <div className="report-page">
        <div className="report-header">
          <div className="report-logo">myK9Show</div>
          <h1 className="report-title">Judge Supply Checklists</h1>
          {showName && <p className="report-subtitle">{showName}</p>}
        </div>
        <p>
          No judge supplies have been configured for this show yet. Open a trial detail page and
          use the "Judge Supplies" section to set them up.
        </p>
      </div>
    );
  }

  return (
    <>
      {pages.map((page, idx) => (
        <div
          key={`${page.trialId}::${page.judgeKey}`}
          className="report-page"
          style={idx < pages.length - 1 ? { pageBreakAfter: 'always' } : undefined}
          data-testid={`supply-page-${page.trialId}-${page.judgeKey}`}
        >
          <div className="report-header">
            <div className="report-logo">myK9Show</div>
            <h1 className="report-title">Judge Supply Checklist</h1>
            {showName && <p className="report-subtitle">{showName}</p>}
          </div>

          <div className="catalog-trial-section">
            <h2 className="catalog-trial-header">
              {page.trialNumber ? `Trial ${page.trialNumber}` : 'Trial'}
              {page.trialDate ? ` — ${formatReportDate(page.trialDate)}` : ''}
            </h2>
            <p className="text-base font-semibold mb-3">Judge: {page.judgeName}</p>

            <JudgePageBody rows={page.rows} />
          </div>

          <div className="report-footer">
            <div className="footer-left">[ ] = check when packed</div>
            <div className="footer-right">Generated by myK9Show</div>
          </div>
        </div>
      ))}
    </>
  );
};

function JudgePageBody({ rows }: { rows: TrialJudgeSupplyRow[] }) {
  const included = rows.filter(r => r.included);

  if (included.length === 0) {
    return (
      <p>
        All template items have been excluded for this judge. Open the trial Judge Supplies dialog
        to add custom items or restore template items.
      </p>
    );
  }

  return (
    <table className="report-table">
      <thead>
        <tr>
          <th style={{ width: '40px' }}>✓</th>
          <th>Item</th>
          <th>Note</th>
        </tr>
      </thead>
      <tbody>
        {included.map(row => (
          <tr key={row.id}>
            <td style={{ textAlign: 'center', fontFamily: 'monospace' }}>[ ]</td>
            <td>{row.item_label}</td>
            <td>{row.note ?? ''}</td>
          </tr>
        ))}
      </tbody>
    </table>
  );
}
