import React from 'react';
import type { ReportProps, ReportEntry } from '@/lib/reports/types';
import {
  formatReportTime,
  sortByPlacement,
  sortByArmband,
  sortByHandler,
  getResultStatusText,
  isQualified,
  countQualified,
} from '@/lib/reports/reportUtils';

export const ResultCatalog: React.FC<ReportProps> = ({
  showName,
  organization,
  showDates,
  allClasses = [],
  entries,
  sortOrder,
}) => {
  if (entries.length === 0) {
    return (
      <div className="report-page">
        <p className="catalog-empty">No results found.</p>
      </div>
    );
  }

  // Group entries by classId
  const entriesByClass = new Map<string, ReportEntry[]>();
  for (const entry of entries) {
    const key = entry.classId ?? 'unknown';
    if (!entriesByClass.has(key)) entriesByClass.set(key, []);
    entriesByClass.get(key)!.push(entry);
  }

  function sortClassEntries(classEntries: ReportEntry[]): ReportEntry[] {
    if (sortOrder === 'armband') return sortByArmband(classEntries);
    if (sortOrder === 'handler') return sortByHandler(classEntries);
    return sortByPlacement(classEntries); // default: 'placement'
  }

  const orgTitle = organization ? `${organization} Scent Work` : 'Scent Work';

  return (
    <div className="report-page">
      <div className="report-header">
        <div className="report-logo">myK9Show</div>
        <h1 className="report-title">{orgTitle} Work Show Results</h1>
        {showName && <p className="report-subtitle">{showName}</p>}
        {showDates && <p className="report-subtitle">{showDates}</p>}
      </div>

      {allClasses.map(cls => {
        const classEntries = sortClassEntries(entriesByClass.get(cls.id) ?? []);
        const className = `${cls.element} ${cls.level}`.trim();
        const qualifiedCount = countQualified(classEntries);

        return (
          <div key={cls.id} className="catalog-class-section">
            <h2 className="catalog-class-header">{className}</h2>
            {classEntries.length === 0 ? (
              <p className="catalog-empty">No results for this class.</p>
            ) : (
              <>
                <table className="report-table">
                  <thead>
                    <tr>
                      <th>Place</th>
                      <th>Armband</th>
                      <th>Call Name</th>
                      <th>Breed</th>
                      <th>Reg #</th>
                      <th>Handler</th>
                      <th>Q</th>
                      <th>Time</th>
                    </tr>
                  </thead>
                  <tbody>
                    {classEntries.map(entry => {
                      const qualified = isQualified(entry);
                      const statusText = getResultStatusText(entry);
                      const placement =
                        entry.finalPlacement && entry.finalPlacement < 9000
                          ? entry.finalPlacement
                          : '';
                      return (
                        <tr key={entry.id}>
                          <td>{placement}</td>
                          <td>{entry.armband}</td>
                          <td>{entry.callName}</td>
                          <td>{entry.breed}</td>
                          <td>{entry.registrationNumber ?? ''}</td>
                          <td>{entry.handler}</td>
                          <td className={qualified ? 'qualified-text' : 'nq-text'}>{statusText}</td>
                          <td>{formatReportTime(entry.searchTimeSeconds)}</td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
                <p className="catalog-class-summary">
                  Entries: {classEntries.length} · Qualified: {qualifiedCount}
                </p>
                {/*
                  INTENT: Each class section ends with a judge signature + date line.
                  After the class wraps the printed catalog is handed to the judge to
                  sign and date, confirming the recorded results. Matches the footer
                  pattern used by JudgesCertification and TrialSecretaryCertification.
                */}
                <div className="form-signature-section catalog-class-signature">
                  <div className="signature-line">
                    <span className="signature-label">Judge&apos;s Signature:</span>
                    <span className="signature-blank" />
                  </div>
                  <div className="signature-line">
                    <span className="signature-label">Date:</span>
                    <span className="signature-blank" />
                  </div>
                </div>
              </>
            )}
          </div>
        );
      })}

      <div className="report-footer">
        <div className="footer-right">Generated by myK9Show</div>
      </div>
    </div>
  );
};
