import React from 'react';
import type { ReportProps, ReportEntry } from '@/lib/reports/types';
import {
  formatReportDate,
  sortByArmband,
  sortByHandler,
  sortByBreed,
} from '@/lib/reports/reportUtils';

export const ShowCatalog: React.FC<ReportProps> = ({
  showName,
  organization,
  showDates,
  clubName,
  allTrials = [],
  entries,
  sortOrder,
}) => {
  if (entries.length === 0) {
    return (
      <div className="report-page">
        <p className="catalog-empty">No entries found.</p>
      </div>
    );
  }

  // Apply sort before grouping so order is preserved within each trial section
  const sorted =
    sortOrder === 'handler'
      ? sortByHandler(entries)
      : sortOrder === 'breed'
        ? sortByBreed(entries)
        : sortByArmband(entries);

  // Group sorted entries by trialId (insertion order preserved)
  const entriesByTrial = new Map<string, ReportEntry[]>();
  for (const entry of sorted) {
    const key = entry.trialId ?? 'unknown';
    if (!entriesByTrial.has(key)) entriesByTrial.set(key, []);
    entriesByTrial.get(key)!.push(entry);
  }

  const orgTitle = organization ? `${organization} Scent Work` : 'Scent Work';

  return (
    <div className="report-page">
      <div className="report-header">
        <div className="report-logo">myK9Show</div>
        <h1 className="report-title">{orgTitle} Show Catalog</h1>
        {showName && <p className="report-subtitle">{showName}</p>}
        {showDates && <p className="report-subtitle">{showDates}</p>}
        {clubName && <p className="report-subtitle">{clubName}</p>}
      </div>

      {allTrials.map(trial => {
        const trialEntries = entriesByTrial.get(trial.id) ?? [];
        return (
          <div key={trial.id} className="catalog-trial-section">
            <h2 className="catalog-trial-header">
              Trial {trial.trialNumber}
              {trial.date ? ` — ${formatReportDate(trial.date)}` : ''}
            </h2>
            {trialEntries.length === 0 ? (
              <p className="catalog-empty">No entries for this trial.</p>
            ) : (
              <table className="report-table">
                <thead>
                  <tr>
                    <th>Armband</th>
                    <th>Call Name</th>
                    <th>Breed</th>
                    <th>Reg #</th>
                    <th>Class</th>
                    <th>Handler</th>
                  </tr>
                </thead>
                <tbody>
                  {trialEntries.map(entry => (
                    <tr key={entry.id}>
                      <td>{entry.armband}</td>
                      <td>{entry.callName}</td>
                      <td>{entry.breed}</td>
                      <td>{entry.registrationNumber ?? ''}</td>
                      <td>{[entry.classElement, entry.classLevel].filter(Boolean).join(' ')}</td>
                      <td>{entry.handler}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            )}
          </div>
        );
      })}

      <div className="report-footer">
        <div className="footer-left">Total Entries: {entries.length}</div>
        <div className="footer-right">Generated by myK9Show</div>
      </div>
    </div>
  );
};
