import React from 'react';
import type { ReportProps } from '@/lib/reports/types';
import { formatReportDate } from '@/lib/reports/reportUtils';
import type { RingRole } from '@/types/volunteer';

const ROLE_COLUMNS: { key: RingRole; label: string }[] = [
  { key: 'Table Steward', label: 'Table Steward' },
  { key: 'Timer',         label: 'Timer Steward' },
  { key: 'Gate Steward',  label: 'Gate Steward'  },
  { key: 'Ring Steward',  label: 'Ring Steward'  },
];

export const StewardReport: React.FC<ReportProps> = ({
  showName,
  clubName,
  trial,
  allClasses = [],
}) => {
  const displayName = clubName ?? showName;
  const trialLabel = trial ? `Trial ${trial.trialNumber}` : '';
  const dateLabel = trial ? formatReportDate(trial.date) : '';

  return (
    <div className="report-page">
      <div className="report-header">
        <div className="report-logo">myK9Show</div>
        <h1 className="report-title">Steward Report</h1>
        {displayName && <p className="report-subtitle">{displayName}</p>}
        {trialLabel && (
          <p className="report-subtitle">
            {trialLabel}
            {dateLabel ? ` — ${dateLabel}` : ''}
          </p>
        )}
      </div>

      <table className="report-table">
        <thead>
          <tr>
            <th>Element</th>
            <th>Level</th>
            <th>Section</th>
            {ROLE_COLUMNS.map(col => (
              <th key={col.key}>{col.label}</th>
            ))}
          </tr>
        </thead>
        <tbody>
          {allClasses.map(cls => (
            <tr key={cls.id}>
              <td>{cls.element}</td>
              <td>{cls.level}</td>
              <td>{cls.section ?? ''}</td>
              {ROLE_COLUMNS.map(col => (
                <td key={col.key}>{cls.stewards?.[col.key] ?? ''}</td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>

      <div className="report-footer">
        <div className="footer-right">Generated by myK9Show</div>
      </div>
    </div>
  );
};
