import React from 'react';
import type { ReportProps } from '@/lib/reports/types';
import { countQualified, formatReportDate } from '@/lib/reports/reportUtils';

export const TrialSecretaryCertification: React.FC<ReportProps> = ({
  showName,
  clubName,
  trial,
  entries,
}) => {
  const trialDate = trial?.date ? formatReportDate(trial.date) : '___________';

  const totalEntries = entries.length;
  const totalRuns = entries.filter(e => e.checkInStatus === 'present').length;
  const totalWithdrawals = entries.filter(e => e.checkInStatus === 'withdrawn').length;
  const totalQualifying = countQualified(entries);

  return (
    <div className="report-page">
      <div className="report-header">
        <div className="report-logo">myK9Show</div>
        <h1 className="report-title">Scent Work Secretary's Certification</h1>
        <p className="report-subtitle">{clubName ?? showName}</p>
      </div>

      <div className="form-section">
        <table className="form-table">
          <tbody>
            <tr>
              <td className="form-label">Date of Trial:</td>
              <td className="form-value">{trialDate}</td>
              <td className="form-label">Trial Number:</td>
              <td className="form-value">Trial {trial?.trialNumber ?? '___'}</td>
            </tr>
          </tbody>
        </table>
      </div>

      <div className="form-section">
        <p className="form-question">
          I certify that the Judge(s) has verified the above information and signed the Judge
          Certification page.
        </p>
        <p style={{ fontSize: '10px', marginTop: '4px' }}>
          Complete the fields below with the correct number of dogs for the entire trial.
        </p>
      </div>

      <div className="form-section" style={{ border: '1px solid #ccc', padding: '12px' }}>
        <table className="form-table">
          <tbody>
            <tr>
              <td
                className="form-value"
                style={{ width: '80px', fontWeight: 'bold', fontSize: '16px' }}
              >
                <span>{totalEntries}</span>
              </td>
              <td className="form-label">Total Entries in the trial</td>
            </tr>
            <tr>
              <td
                className="form-value"
                style={{ width: '80px', fontWeight: 'bold', fontSize: '16px' }}
              >
                <span>{totalRuns}</span>
              </td>
              <td className="form-label">Total Runs (starters/participants) in the trial</td>
            </tr>
            <tr>
              <td
                className="form-value"
                style={{ width: '80px', fontWeight: 'bold', fontSize: '16px' }}
              >
                <span>{totalWithdrawals}</span>
              </td>
              <td className="form-label">Total Withdrawals from the trial</td>
            </tr>
            <tr>
              <td
                className="form-value"
                style={{ width: '80px', fontWeight: 'bold', fontSize: '16px' }}
              >
                <span>{totalQualifying}</span>
              </td>
              <td className="form-label">Total Qualifying scores</td>
            </tr>
          </tbody>
        </table>
      </div>

      <div className="form-signature-section">
        <div className="signature-line">
          <span className="signature-label">Trial Secretary's Signature:</span>
          <span className="signature-blank" />
        </div>
      </div>

      <div className="report-footer">
        <div className="footer-right">Generated by myK9Show — Page 1 of 1</div>
      </div>
    </div>
  );
};
