import React from 'react';
import type { ReportProps } from '@/lib/reports/types';
import { formatReportDate } from '@/lib/reports/reportUtils';
import {
  AKC_TRIAL_SECRETARY_CANONICAL_FORM,
  resolveAKCTrialSecretaryReportPolicy,
} from '@/features/organization-forms/akcTrialSecretaryReportPolicy';

export const TrialSecretaryReport: React.FC<ReportProps> = ({
  showName,
  clubName,
  trial,
  entries,
}) => {
  const trialDate = trial?.date ? formatReportDate(trial.date) : '___________';
  const judgeName = trial?.judgeName ?? '___________';
  const policy = resolveAKCTrialSecretaryReportPolicy(trial?.date, entries);

  return (
    <div className="report-page">
      <div className="report-header">
        <div className="report-logo">myK9Show</div>
        <h1 className="report-title">Report of Scent Work Trial</h1>
        <p className="report-subtitle">AKC Trial Secretary Report</p>
      </div>

      <div className="form-section">
        <p style={{ fontSize: '10px' }}>{AKC_TRIAL_SECRETARY_CANONICAL_FORM.timing}</p>
        <p className="form-address">Send to: {AKC_TRIAL_SECRETARY_CANONICAL_FORM.address}</p>
        <p style={{ fontSize: '10px' }}>Form {AKC_TRIAL_SECRETARY_CANONICAL_FORM.revision}</p>
      </div>

      {!policy.ok && (
        <div className="form-section" role="alert">
          {policy.recovery}
        </div>
      )}

      <table className="form-table">
        <tbody>
          <tr>
            <td className="form-label">Name of Club:</td>
            <td className="form-value">{clubName ?? showName ?? '___________'}</td>
          </tr>
          <tr>
            <td className="form-label">Date of Trial:</td>
            <td className="form-value">{trialDate}</td>
          </tr>
          <tr>
            <td className="form-label">Trial Number:</td>
            <td className="form-value">Trial {trial?.trialNumber ?? '___'}</td>
          </tr>
          <tr>
            <td className="form-label">Total # of Entries at closing:</td>
            <td className="form-value">{entries.length}</td>
          </tr>
          {policy.ok && (
            <>
              <tr>
                <td className="form-label"># Withdrawn Entries after closing:</td>
                <td className="form-value">{policy.excludedRuns}</td>
              </tr>
              <tr>
                <td className="form-label"># of Entries for which service fees are due:</td>
                <td className="form-value">{policy.paidRuns}</td>
              </tr>
            </>
          )}
          <tr>
            <td className="form-label">Judge Name:</td>
            <td className="form-value">{judgeName}</td>
          </tr>
          {policy.ok && (
            <tr>
              <td className="form-label" colSpan={2}>
                {`$${policy.formattedRate} per run × ${policy.paidRuns} paid runs = $${policy.formattedTotal} Total Service Fees`}
              </td>
            </tr>
          )}
        </tbody>
      </table>

      <div className="form-section">
        <p className="form-question">
          Did the judge below give notice on the result certification of their inability to judge?
          Or was any complaint filed against the AKC Club, Event Secretary, Show Chair, or Judge?
        </p>
        <div className="form-checkbox-row">
          <span className="form-checkbox">☐ Yes</span>
          <span className="form-checkbox">☐ No</span>
        </div>
        <div className="form-blank-line" />
      </div>

      <div className="form-section">
        <p className="form-question">
          Were there any complaints about this event filed with the AKC?
        </p>
        <div className="form-checkbox-row">
          <span className="form-checkbox">☐ Yes</span>
          <span className="form-checkbox">☐ No</span>
        </div>
        <div className="form-blank-line" />
      </div>

      <div className="form-signature-section">
        <div className="signature-line">
          <span className="signature-label">Trial Secretary Signature:</span>
          <span className="signature-blank" />
        </div>
        <div className="signature-line">
          <span className="signature-label">Date:</span>
          <span className="signature-blank" />
        </div>
      </div>

      <div className="report-footer">
        <div className="footer-right">Generated by myK9Show — Page 1 of 1</div>
      </div>
    </div>
  );
};
