import React from 'react';
import type { ReportProps } from '@/lib/reports/types';
import { formatReportDate } from '@/lib/reports/reportUtils';

const AKC_ADDRESS =
  'The American Kennel Club, Event Operations, 8051 Arco Corporate Dr, Suite 100, Raleigh, NC 27617-3390';
const AKC_FEE_PER_ENTRY = 3.5;

export const TrialSecretaryReport: React.FC<ReportProps> = ({
  showName,
  clubName,
  trial,
  entries,
}) => {
  const trialDate = trial?.date ? formatReportDate(trial.date) : '___________';
  const judgeName = trial?.judgeName ?? '___________';
  const entryCount = entries.length;
  const totalFee = (entryCount * AKC_FEE_PER_ENTRY).toFixed(2);

  return (
    <div className="report-page">
      <div className="report-header">
        <div className="report-logo">myK9Show</div>
        <h1 className="report-title">Report of Scent Work Trial</h1>
        <p className="report-subtitle">AKC Trial Secretary Report</p>
      </div>

      <div className="form-section">
        <p style={{ fontSize: '10px' }}>
          Upon completion of a Scent Work Trial, the Superintendent/Event Secretary shall complete a
          copy of this form for each event (one event per form) and mail the marked and signed
          original and judge copies to AKC Event Operations within 15 days of the event.
        </p>
        <p className="form-address">Send to: {AKC_ADDRESS}</p>
      </div>

      <table className="form-table">
        <tbody>
          <tr>
            <td className="form-label">Name of Club:</td>
            <td className="form-value">{clubName ?? showName ?? '___________'}</td>
          </tr>
          <tr>
            <td className="form-label">Date of Trial:</td>
            <td className="form-value">{trialDate}</td>
          </tr>
          <tr>
            <td className="form-label">Trial Number:</td>
            <td className="form-value">Trial {trial?.trialNumber ?? '___'}</td>
          </tr>
          <tr>
            <td className="form-label">Number of Entries:</td>
            <td className="form-value">{entryCount}</td>
          </tr>
          <tr>
            <td className="form-label">Judge Name:</td>
            <td className="form-value">{judgeName}</td>
          </tr>
          <tr>
            <td className="form-label" colSpan={2}>
              ${AKC_FEE_PER_ENTRY.toFixed(2)} per entry × {entryCount} entries = ${totalFee} Total Service Charge
            </td>
          </tr>
        </tbody>
      </table>

      <div className="form-section">
        <p className="form-question">
          Did the judge below give notice on the result certification of their inability to judge?
          Or was any complaint filed against the AKC Club, Event Secretary, Show Chair, or Judge?
        </p>
        <div className="form-checkbox-row">
          <span className="form-checkbox">☐ Yes</span>
          <span className="form-checkbox">☑ No</span>
        </div>
        <div className="form-blank-line" />
      </div>

      <div className="form-section">
        <p className="form-question">
          Were there any complaints about this event filed with the AKC?
        </p>
        <div className="form-checkbox-row">
          <span className="form-checkbox">☐ Yes</span>
          <span className="form-checkbox">☑ No</span>
        </div>
        <div className="form-blank-line" />
      </div>

      <div className="form-signature-section">
        <div className="signature-line">
          <span className="signature-label">Trial Secretary Signature:</span>
          <span className="signature-blank" />
        </div>
        <div className="signature-line">
          <span className="signature-label">Date:</span>
          <span className="signature-blank" />
        </div>
      </div>

      <div className="report-footer">
        <div className="footer-right">Generated by myK9Show — Page 1 of 1</div>
      </div>
    </div>
  );
};
