// Throwaway: compare three production landing-page structures via ?variant=A|B|C.
// Isolated from the application at the user's request. All conversion actions are stubs.
const names = ['A — Warm & focused', 'B — Product first', 'C — Choose your path'];
const keys = ['A', 'B', 'C'];
let current = Math.max(0, keys.indexOf(new URLSearchParams(location.search).get('variant') ?? 'A'));
const app = document.querySelector<HTMLElement>('#app')!;
const photo = '<img class="dogs" src="./hero-ziva-tera.jpg" alt="Ziva and Tera standing together in an autumn field">';
const action = (label: string, kind = 'primary', intent = 'club') => `<button class="button ${kind}" data-intent="${intent}">${label} <span aria-hidden="true">↗</span></button>`;
const header = () => `<header><a class="brand" href="?variant=${keys[current]}"><span class="seal">✳</span> myK9Show</a><nav aria-label="Main navigation"><a href="#how">How it works</a><a href="#fees">Fees</a><button data-intent="signin">Sign in</button></nav>${action('Bring your club aboard')}</header>`;
const proof = () => '<div class="proof"><span>From the RyKris team behind mySWT & myNWT</span><span>Building scent-sport software since 2013</span></div>';
const preview = () => `<div class="product"><div class="product-top"><span>myK9Show / Show workbench</span><span class="tag">ILLUSTRATIVE DATA</span></div><div class="product-body"><span class="eyebrow">YOUR NEXT TRIAL</span><h3>Autumn Scent Work Trial</h3><p>Saturday, October 24 · Sample club</p><div class="metrics"><div><b>84</b><span>Entries accepted</span></div><div><b>3</b><span>Rings prepared</span></div><div><b>2</b><span>Items to review</span></div></div><h4>Before the first dog runs</h4><div class="task"><span class="check">✓</span><span>Entries reviewed</span><span>Ready</span></div><div class="task"><span class="check">✓</span><span>Judges assigned</span><span>Ready</span></div><div class="task"><span class="pending">•</span><span>Confirm ring assignments</span><span>Review</span></div><div class="task"><span class="pending">•</span><span>Check final running order</span><span>Review</span></div><p class="caption">Concept illustration of the workflow, not a screenshot of the current app.</p></div></div>`;
const steps = () => `<section class="section" id="how"><div class="section-heading"><span class="eyebrow">ONE TRIAL. ONE CONNECTED WORKFLOW.</span><h2>Less administration.<br>More time for the dogs.</h2></div><div class="steps"><article><span class="number">01 / BEFORE THE SHOW</span><h3>Get entries in order.</h3><p>Set up your trial, accept online entries, and prepare your catalog and running orders.</p></article><article><span class="number">02 / AT THE RING</span><h3>Keep the day moving.</h3><p>Give judges and stewards a focused ringside view. Prepare devices online before scoring offline.</p></article><article><span class="number">03 / AFTER THE LAST DOG</span><h3>Finish with less paperwork.</h3><p>Bring scores and placements into the same workflow, ready for results and reporting.</p></article></div></section>`;
const faq = () => `<section class="section questions" id="fees"><div><span class="eyebrow">A FEW THINGS TO KNOW</span><h2>Clear before<br>you commit.</h2><p>No need to learn the whole platform<br>to decide whether it fits your club.</p></div><div><details open><summary>How do the fees work?</summary><p>Exhibitors pay a 7% service fee on top of entry fees at checkout. Clubs receive their entry fees in full.</p><a href="https://myk9show.com/fees" target="_blank" rel="noopener">Read the full fee explanation ↗</a></details><details><summary>Which sports is this for?</summary><p>The launch focus is AKC Scent Work, UKC Nosework, and ASCA Scent Detection. Confirm support for your event with the team before onboarding.</p></details><details><summary>What works without a connection?</summary><p>Prepare and load ringside devices while online. Judges can then record scores without a signal; sharing updates between devices needs a connection. Confirm the supported setup with the team.</p></details><details><summary>How does my club get started?</summary><p>Create an account and request club onboarding through the existing myK9Show flow. The team reviews your request and helps with the next step.</p></details></div></section>`;
const ending = () => `<section class="closing"><span class="eyebrow">FOR YOUR NEXT SCENT-WORK TRIAL</span><h2>Let's make show day<br>feel a little easier.</h2><div class="actions">${action('Bring your club aboard')}${action('Find a show', 'light', 'shows')}</div></section><footer><a class="brand" href="#">myK9Show</a><p>Built by RyKris. Made for dog people.</p><div><a href="https://myk9show.com/privacy">Privacy</a><a href="https://myk9show.com/terms">Terms</a><button data-intent="contact">Contact</button></div></footer><p class="review-note">Review concept only. Launch availability and product claims require sign-off. No accounts, requests, or payments are created here.</p>`;
function variantA() { return `${header()}<section class="hero warm"><div class="hero-copy"><span class="eyebrow">SCENT-WORK TRIALS, MADE SIMPLER</span><h1>Less paperwork.<br><em>More dog time.</em></h1><p>From the first entry to the final placement, bring your club, exhibitors, and ringside team together in myK9Show.</p><div class="actions">${action('Bring your club aboard')}${action('Find a show', 'secondary', 'shows')}</div><p class="caption">AKC Scent Work · UKC Nosework · ASCA Scent Detection</p></div><figure>${photo}<figcaption>Ziva & Tera · The reason we do this.</figcaption></figure></section>${proof()}${steps()}<section class="section showcase"><div><span class="eyebrow">BUILT AROUND THE SECRETARY'S DAY</span><h2>Know what's ready.<br>See what's next.</h2><p>Entries, ring preparation, and results belong to the same trial. Keep the details together so your team can focus on the day ahead.</p>${action('Explore the workflow','secondary','demo')}</div>${preview()}</section>${faq()}${ending()}`; }
function variantB() { return `${header()}<section class="hero product-led"><div class="hero-copy"><span class="eyebrow">FOR CLUBS & TRIAL SECRETARIES</span><h1>A calmer way<br>to run your<br><em>next trial.</em></h1><p>Online entries. Prepared rings. Results in one place. One connected workflow from premium list to final placements.</p><div class="actions">${action('Bring your club aboard')}${action('See the workflow','secondary','demo')}</div><p class="caption">Exhibiting? <button class="text-link" data-intent="shows">Find your next show ↗</button></p></div>${preview()}</section>${proof()}<section class="photo-band">${photo}<div><span class="eyebrow">THE SOFTWARE SHOULD FADE INTO THE BACKGROUND</span><h2>You handle the dogs.<br>We'll help with the details.</h2></div></section>${steps()}${faq()}${ending()}`; }
function variantC() { return `${header()}<section class="path-hero"><span class="eyebrow">MYK9SHOW · SCENT WORK FIRST</span><h1>Your trial.<br><em>All together.</em></h1><p>For the people organizing the day,<br>and the people stepping up to the start line.</p><div class="paths"><article><span class="eyebrow">CLUBS & SECRETARIES</span><h2>I'm running<br>a trial.</h2><p>Bring entries, ringside work, and results into one place.</p>${action('Bring your club aboard')}</article><figure>${photo}<figcaption>Made for moments like these.</figcaption></figure><article><span class="eyebrow">EXHIBITORS</span><h2>I'm entering<br>a trial.</h2><p>Find a show, enter your dogs, and follow your show day.</p>${action('Find a show','secondary','shows')}</article></div><p class="caption">Judges and stewards: <button class="text-link" data-intent="signin">Sign in for your assigned events ↗</button></p></section>${proof()}${steps()}${faq()}${ending()}`; }
const messages: Record<string,string> = {
 club: 'On the production page, this would take visitors to the existing club onboarding section: create an account or sign in, then request onboarding. This prototype does not submit a request.',
 shows: 'On the production page, this would open the existing /shows directory. Promote this action when the public list contains launch-ready events; the current live list includes load-test names.',
 signin: 'On the production page, this would open the existing sign-in flow. No sign-in occurs in this prototype.',
 demo: 'This concept uses an illustrative workbench. Before launch, replace it with a verified, sanitized product screenshot or a short walkthrough of the real workflow.',
 contact: 'On the production page, this would use the existing contact channel. This prototype sends no message.'
};
function render() {
 document.body.dataset.variant = keys[current];
 app.innerHTML = [variantA,variantB,variantC][current]();
 document.querySelector('#variant-name')!.textContent = names[current];
 document.querySelectorAll<HTMLButtonElement>('[data-intent]').forEach(button => button.addEventListener('click', () => {
  document.querySelector('#notice-copy')!.textContent = messages[button.dataset.intent!] ?? messages.club;
  document.querySelector<HTMLDialogElement>('#notice')!.showModal();
 }));
}
function cycle(delta:number) {current = (current + delta + 3) % 3; const url = new URL(location.href); url.searchParams.set('variant',keys[current]); history.replaceState(null,'',url); render(); window.scrollTo(0,0);}
document.querySelector('#prev')!.addEventListener('click',()=>cycle(-1));
document.querySelector('#next')!.addEventListener('click',()=>cycle(1));
document.addEventListener('keydown',event=>{if(document.querySelector('dialog[open]') || (event.target instanceof HTMLElement && (event.target.matches('input,textarea,select') || event.target.isContentEditable))) return; if(event.key==='ArrowRight') cycle(1); if(event.key==='ArrowLeft') cycle(-1);});
render();
