import { UserRole } from '@/types/auth-types';

export const PERSON_ROLES: { value: UserRole; label: string }[] = [
  { value: UserRole.EXHIBITOR, label: 'Exhibitor' },
  { value: UserRole.JUDGE, label: 'Judge' },
  { value: UserRole.CHAIRMAN, label: 'Chairman' },
  { value: UserRole.SECRETARY, label: 'Secretary' },
  { value: UserRole.STEWARD, label: 'Steward' },
  { value: UserRole.CLUB_ADMIN, label: 'Club Admin' },
  { value: UserRole.SITE_ADMIN, label: 'Site Admin' },
];

export const US_STATES = [
  'AL',
  'AK',
  'AZ',
  'AR',
  'CA',
  'CO',
  'CT',
  'DE',
  'FL',
  'GA',
  'HI',
  'ID',
  'IL',
  'IN',
  'IA',
  'KS',
  'KY',
  'LA',
  'ME',
  'MD',
  'MA',
  'MI',
  'MN',
  'MS',
  'MO',
  'MT',
  'NE',
  'NV',
  'NH',
  'NJ',
  'NM',
  'NY',
  'NC',
  'ND',
  'OH',
  'OK',
  'OR',
  'PA',
  'RI',
  'SC',
  'SD',
  'TN',
  'TX',
  'UT',
  'VT',
  'VA',
  'WA',
  'WV',
  'WI',
  'WY',
];
