#!/usr/bin/env -S npx tsx
/**
 * import-judges.ts
 *
 * Converts the AKC/UKC judge directory CSV into a SQL migration file.
 * Outputs SQL to stdout — safe by default, no DB connection required.
 *
 * Usage:
 *   npx tsx scripts/import-judges.ts                     # default CSV path
 *   npx tsx scripts/import-judges.ts path/to/judges.csv  # custom CSV path
 *
 * When ready to ship:
 *   npx tsx scripts/import-judges.ts > supabase/migrations/NNN_seed_akc_ukc_judges.sql
 *   supabase db push --password "$SUPABASE_DB_PASSWORD"
 */

import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

const csvPath = process.argv[2]
  ? resolve(process.argv[2])
  : resolve('supabase/seed-data/akc-ukc-judges.csv');

interface JudgeRow {
  judge_number: string;
  first_name: string;
  last_name: string;
  email: string;
  organization: string;
  level: string;
  disciplines: string[];
  date_obtained: string | null;
  expiration_date: string | null;
}

function parseCsv(path: string): JudgeRow[] {
  const lines = readFileSync(path, 'utf8').split('\n');
  const rows: JudgeRow[] = [];
  let headers: string[] = [];

  for (const raw of lines) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;

    // Respect quoted fields with commas by splitting carefully
    const cols = line.split(',').map(c => c.trim());

    if (!headers.length) {
      headers = cols;
      continue;
    }

    const r: Record<string, string> = {};
    headers.forEach((h, i) => {
      r[h] = cols[i] ?? '';
    });

    rows.push({
      judge_number: r.judge_number,
      first_name: r.first_name,
      last_name: r.last_name,
      email: r.email,
      organization: r.organization,
      level: r.level,
      disciplines: r.disciplines ? r.disciplines.split('|').map(d => d.trim()).filter(Boolean) : [],
      date_obtained: r.date_obtained || null,
      expiration_date: r.expiration_date || null,
    });
  }

  return rows;
}

function sq(val: string | null): string {
  if (val === null) return 'NULL';
  return `'${val.replace(/'/g, "''")}'`;
}

function pgArray(vals: string[]): string {
  return `ARRAY[${vals.map(sq).join(', ')}]::text[]`;
}

function generateSql(rows: JudgeRow[]): string {
  if (!rows.length) {
    return '-- No judge rows found in CSV. Populate supabase/seed-data/akc-ukc-judges.csv and re-run.\n';
  }

  // Group rows by judge_number so each judge gets one DO block
  const byJudge = new Map<string, JudgeRow[]>();
  for (const row of rows) {
    const existing = byJudge.get(row.judge_number) ?? [];
    existing.push(row);
    byJudge.set(row.judge_number, existing);
  }

  const blocks: string[] = [
    `-- AKC & UKC Judge Directory seed`,
    `-- Generated by scripts/import-judges.ts — do not hand-edit; edit the CSV instead.`,
    `-- Idempotent: safe to re-run; uses judge_number for de-duplication.\n`,
  ];

  for (const [judgeNumber, quals] of byJudge) {
    const { first_name, last_name, email } = quals[0];
    const qualInserts = quals.map(q => `
    IF NOT EXISTS (
      SELECT 1 FROM judge_qualifications
      WHERE person_id = v_person_id
        AND organization = ${sq(q.organization)}
        AND qualification_level = ${sq(q.level)}
    ) THEN
      INSERT INTO judge_qualifications
        (person_id, organization, qualification_level, disciplines, date_obtained, expiration_date, is_active)
      VALUES (
        v_person_id,
        ${sq(q.organization)},
        ${sq(q.level)},
        ${pgArray(q.disciplines)},
        ${sq(q.date_obtained)},
        ${sq(q.expiration_date)},
        TRUE
      );
    END IF;`).join('');

    blocks.push(`DO $$
DECLARE
  v_person_id UUID;
BEGIN
  -- ${first_name} ${last_name} (${judgeNumber})
  SELECT id INTO v_person_id FROM people WHERE judge_number = ${sq(judgeNumber)};
  IF v_person_id IS NULL THEN
    INSERT INTO people (first_name, last_name, email, judge_number, roles)
    VALUES (${sq(first_name)}, ${sq(last_name)}, ${email ? sq(email) : 'NULL'}, ${sq(judgeNumber)}, ARRAY['judge']::text[])
    RETURNING id INTO v_person_id;
  END IF;
${qualInserts}
END $$;`);
  }

  return blocks.join('\n') + '\n';
}

const rows = parseCsv(csvPath);
process.stdout.write(generateSql(rows));
if (rows.length) {
  process.stderr.write(`\n-- Processed ${rows.length} qualification row(s) for ${new Set(rows.map(r => r.judge_number)).size} judge(s).\n`);
}
