#!/usr/bin/env -S npx tsx
/**
 * import-judges.ts
 *
 * Converts the AKC/UKC judge directory CSV into a SQL migration file.
 * Outputs SQL to stdout — safe by default, no DB connection required.
 *
 * Usage:
 *   npx tsx scripts/import-judges.ts                     # default CSV path
 *   npx tsx scripts/import-judges.ts path/to/judges.csv  # custom CSV path
 *
 * When ready to ship:
 *   npx tsx scripts/import-judges.ts > supabase/migrations/NNN_seed_akc_ukc_judges.sql
 *   supabase db push --password "$SUPABASE_DB_PASSWORD"
 *
 * Schema notes (post migration 070):
 *   - judge_number lives on judge_qualifications (one per org), NOT on people
 *   - People are de-duped by email; same-person multi-org rows share an email
 *   - Person lookup order: email → existing qualification by judge_number+org → insert new
 */

import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

const csvPath = process.argv[2]
  ? resolve(process.argv[2])
  : resolve('supabase/seed-data/akc-ukc-judges.csv');

interface QualRow {
  judge_number: string;
  first_name: string;
  last_name: string;
  email: string;
  organization: string;
  level: string;
  disciplines: string[];
  date_obtained: string | null;
  expiration_date: string | null;
}

/** RFC 4180-compliant single-line CSV parser — handles quoted fields with commas and escaped quotes. */
function splitCsvLine(line: string): string[] {
  const cols: string[] = [];
  let cur = '';
  let inQuotes = false;

  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (ch === '"') {
      if (inQuotes && line[i + 1] === '"') {
        cur += '"';
        i++; // skip escaped quote
      } else {
        inQuotes = !inQuotes;
      }
    } else if (ch === ',' && !inQuotes) {
      cols.push(cur.trim());
      cur = '';
    } else {
      cur += ch;
    }
  }
  cols.push(cur.trim());
  return cols;
}

function parseCsv(path: string): QualRow[] {
  const lines = readFileSync(path, 'utf8').split('\n');
  const rows: QualRow[] = [];
  let headers: string[] = [];

  for (const raw of lines) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;

    const cols = splitCsvLine(line);

    if (!headers.length) {
      headers = cols;
      continue;
    }

    const r: Record<string, string> = {};
    headers.forEach((h, i) => {
      r[h] = cols[i] ?? '';
    });

    rows.push({
      judge_number: r.judge_number,
      first_name: r.first_name,
      last_name: r.last_name,
      email: r.email,
      organization: r.organization,
      level: r.level,
      disciplines: r.disciplines ? r.disciplines.split('|').map(d => d.trim()).filter(Boolean) : [],
      date_obtained: r.date_obtained || null,
      expiration_date: r.expiration_date || null,
    });
  }

  return rows;
}

function sq(val: string | null): string {
  if (val === null) return 'NULL';
  return `'${val.replace(/'/g, "''")}'`;
}

function pgArray(vals: string[]): string {
  return `ARRAY[${vals.map(sq).join(', ')}]::text[]`;
}

function generateSql(rows: QualRow[]): string {
  if (!rows.length) {
    return '-- No judge rows found in CSV. Populate supabase/seed-data/akc-ukc-judges.csv and re-run.\n';
  }

  // Group qualification rows by person.
  // - With email: key by email — safe cross-org dedup.
  // - Without email: key by judge_number|organization — each row is its own block.
  //   Grouping by name would silently merge two different judges who share a name.
  //   A multi-org no-email judge ends up with separate blocks (and separate people rows);
  //   a stderr warning tells the importer to add email to merge them.
  const byPerson = new Map<string, QualRow[]>();
  const noEmailNameCount = new Map<string, number>();

  for (const row of rows) {
    let key: string;
    if (row.email) {
      key = `email:${row.email}`;
    } else {
      key = `jnum:${row.judge_number}|${row.organization}`;
      const nameKey = `${row.first_name}|${row.last_name}`;
      noEmailNameCount.set(nameKey, (noEmailNameCount.get(nameKey) ?? 0) + 1);
    }
    const existing = byPerson.get(key) ?? [];
    existing.push(row);
    byPerson.set(key, existing);
  }

  // Warn about no-email rows that share a name — they may be the same person.
  for (const [nameKey, count] of noEmailNameCount) {
    if (count > 1) {
      const [first, last] = nameKey.split('|');
      process.stderr.write(
        `WARNING: ${count} rows for "${first} ${last}" have no email — ` +
          `each will create a separate people row. Add email to merge them.\n`,
      );
    }
  }

  const blocks: string[] = [
    `-- AKC & UKC Judge Directory seed`,
    `-- Generated by scripts/import-judges.ts — do not hand-edit; edit the CSV instead.`,
    `-- Idempotent: safe to re-run. Person lookup: email → existing qualification → insert.`,
    `-- judge_number is stored per-org on judge_qualifications (migration 070).\n`,
  ];

  for (const [personKey, quals] of byPerson) {
    const { first_name, last_name, email } = quals[0];
    const label = `${first_name} ${last_name}${email ? ` <${email}>` : ` (no email — ${quals[0].judge_number}/${quals[0].organization})`}`;

    // Fallback lookup via first qualification's judge_number + org (when no email provided)
    const fallbackLookup = email
      ? ''
      : `
  -- No email: fall back to existing qualification lookup
  IF v_person_id IS NULL THEN
    SELECT person_id INTO v_person_id
    FROM judge_qualifications
    WHERE judge_number = ${sq(quals[0].judge_number)} AND organization = ${sq(quals[0].organization)}
    LIMIT 1;
  END IF;`;

    const qualInserts = quals.map(q => `
  IF NOT EXISTS (
    SELECT 1 FROM judge_qualifications
    WHERE person_id = v_person_id
      AND organization = ${sq(q.organization)}
      AND qualification_level = ${sq(q.level)}
  ) THEN
    INSERT INTO judge_qualifications
      (person_id, organization, qualification_level, disciplines,
       date_obtained, expiration_date, is_active, judge_number)
    VALUES (
      v_person_id,
      ${sq(q.organization)},
      ${sq(q.level)},
      ${pgArray(q.disciplines)},
      ${sq(q.date_obtained)},
      ${sq(q.expiration_date)},
      TRUE,
      ${sq(q.judge_number)}
    );
  END IF;`).join('');

    blocks.push(`DO $$
DECLARE
  v_person_id UUID;
BEGIN
  -- ${label}
  ${email ? `SELECT id INTO v_person_id FROM people WHERE email = ${sq(email)};` : `-- (no email — using qualification lookup below)`}${fallbackLookup}
  IF v_person_id IS NULL THEN
    INSERT INTO people (first_name, last_name, email, roles)
    VALUES (${sq(first_name)}, ${sq(last_name)}, ${email ? sq(email) : 'NULL'}, ARRAY['judge']::text[])
    RETURNING id INTO v_person_id;
  END IF;
${qualInserts}
END $$;`);
  }

  return blocks.join('\n') + '\n';
}

const rows = parseCsv(csvPath);
process.stdout.write(generateSql(rows));
if (rows.length) {
  const judgeCount = new Set(rows.map(r => r.email || `${r.first_name}|${r.last_name}`)).size;
  process.stderr.write(`-- Processed ${rows.length} qualification row(s) for ${judgeCount} judge(s).\n`);
}
