import React, { useState, useCallback, useRef, useEffect } from 'react';
import { X, Info, Globe, Key, Smartphone, RefreshCw, CheckCircle, Loader2 } from 'lucide-react';
import './shared-dialog.css';
import { productVersion, formattedBuildDate } from '../../config/appVersion';
import { logger } from '@/utils/logger';

const PUSH_USER_ID_KEY = 'push_user_id'; // Must match pushNotificationService.ts

interface AboutDialogProps {
  isOpen: boolean;
  onClose: () => void;
  licenseKey?: string;
}

export const AboutDialog: React.FC<AboutDialogProps> = ({ isOpen, onClose, licenseKey }) => {
  const [updateStatus, setUpdateStatus] = useState<
    'idle' | 'checking' | 'up-to-date' | 'update-available' | 'updating'
  >('idle');
  const statusRef = useRef(updateStatus);
  useEffect(() => {
    statusRef.current = updateStatus;
  }, [updateStatus]);
  const timersRef = useRef<ReturnType<typeof setTimeout>[]>([]);

  // Clear all pending timers on unmount
  useEffect(() => {
    return () => {
      timersRef.current.forEach(clearTimeout);
      timersRef.current = [];
    };
  }, []);

  // When dialog opens, check if there's already a waiting SW
  useEffect(() => {
    if (!isOpen || !('serviceWorker' in navigator)) return;

    const checkWaiting = async () => {
      try {
        const registration = await navigator.serviceWorker.getRegistration();
        if (registration?.waiting) {
          setUpdateStatus('update-available');
        }
      } catch {
        // Ignore
      }
    };
    checkWaiting();

    return () => {
      setUpdateStatus('idle');
    };
  }, [isOpen]);

  // Load device ID from localStorage (generated by push notification service)
  // Read synchronously since localStorage is sync and component re-renders when isOpen changes
  const deviceId = isOpen ? localStorage.getItem(PUSH_USER_ID_KEY) : null;

  const checkForUpdates = useCallback(async () => {
    if (!('serviceWorker' in navigator)) return;

    setUpdateStatus('checking');
    try {
      const registration = await navigator.serviceWorker.getRegistration();
      if (!registration) {
        setUpdateStatus('idle');
        return;
      }

      if (registration.waiting) {
        setUpdateStatus('update-available');
        return;
      }

      let foundUpdate = false;

      const trackInstalling = (sw: ServiceWorker) => {
        foundUpdate = true;
        const onStateChange = () => {
          if (sw.state === 'installed') {
            sw.removeEventListener('statechange', onStateChange);
            setUpdateStatus('update-available');
          }
        };
        if (sw.state === 'installed') {
          setUpdateStatus('update-available');
        } else {
          sw.addEventListener('statechange', onStateChange);
        }
      };

      if (registration.installing) {
        trackInstalling(registration.installing);
        return;
      }

      const onUpdateFound = () => {
        registration.removeEventListener('updatefound', onUpdateFound);
        if (registration.installing) {
          trackInstalling(registration.installing);
        }
      };
      registration.addEventListener('updatefound', onUpdateFound);

      await registration.update();

      const checkTimer = setTimeout(() => {
        registration.removeEventListener('updatefound', onUpdateFound);
        if (!foundUpdate) {
          setUpdateStatus('up-to-date');
          const resetTimer = setTimeout(() => {
            if (statusRef.current === 'up-to-date') setUpdateStatus('idle');
          }, 4000);
          timersRef.current.push(resetTimer);
        }
      }, 3000);
      timersRef.current.push(checkTimer);
    } catch (error) {
      logger.warn('[About] Update check failed:', error);
      setUpdateStatus('idle');
    }
  }, []);

  const applyUpdate = useCallback(async () => {
    setUpdateStatus('updating');
    try {
      const registration = await navigator.serviceWorker.getRegistration();
      if (!registration?.waiting) {
        setUpdateStatus('up-to-date');
        const timer = setTimeout(() => {
          if (statusRef.current === 'up-to-date') setUpdateStatus('idle');
        }, 4000);
        timersRef.current.push(timer);
        return;
      }

      registration.waiting.postMessage({ type: 'SKIP_WAITING' });

      navigator.serviceWorker.addEventListener('controllerchange', () => {
        window.location.reload();
      });

      const timer = setTimeout(() => window.location.reload(), 3000);
      timersRef.current.push(timer);
    } catch (error) {
      logger.warn('[About] Failed to apply update:', error);
      window.location.reload();
    }
  }, []);

  if (!isOpen) return null;

  return (
    <div className="dialog-overlay about-dialog-overlay" onClick={onClose}>
      <div
        className="dialog-container"
        onClick={e => e.stopPropagation()}
        style={{
          maxWidth: '420px',
          margin: 'auto',
          animation: 'dialogSlideIn 0.2s ease-out',
        }}
      >
        <div className="dialog-header">
          <div className="dialog-title">
            <Info className="title-icon" />
            <span>About</span>
          </div>
          <button className="close-button" onClick={onClose}>
            <X className="h-5 w-5" />
          </button>
        </div>

        <div className="dialog-content">
          {/* App Info */}
          <div style={{ textAlign: 'center', marginBottom: '1.25rem' }}>
            {/* Logo */}
            <div
              style={{
                display: 'flex',
                justifyContent: 'center',
                marginBottom: '0.75rem',
              }}
            >
              <div
                style={{
                  width: '72px',
                  height: '72px',
                  borderRadius: '16px',
                  background: 'var(--muted)',
                  padding: '8px',
                  boxShadow: '0 4px 12px rgba(0, 0, 0, 0.1)',
                  border: '2px solid var(--border)',
                }}
              >
                <img
                  src="/myK9Q-teal-192.png"
                  alt="myK9Q Logo"
                  style={{
                    width: '100%',
                    height: '100%',
                    objectFit: 'contain',
                  }}
                />
              </div>
            </div>

            <h2
              style={{
                fontSize: '1.75rem',
                fontWeight: 700,
                marginBottom: '0.25rem',
                color: 'var(--foreground)',
                textAlign: 'center',
                margin: '0 auto 0.25rem auto',
                width: '100%',
              }}
            >
              myK9Q
            </h2>
            <p
              style={{
                fontSize: '1rem',
                color: 'var(--primary)',
                fontWeight: 600,
                letterSpacing: '0.05em',
                textAlign: 'center',
                margin: '0 auto 0.5rem auto',
                width: '100%',
              }}
            >
              Queue & Qualify
            </p>
            <p
              style={{
                fontSize: '0.875rem',
                color: 'var(--muted-foreground)',
                marginBottom: '0.25rem',
                textAlign: 'center',
                margin: '0 auto 0.25rem auto',
                width: '100%',
              }}
            >
              Version {productVersion}
            </p>
            <p
              style={{
                fontSize: '0.75rem',
                color: 'var(--muted-foreground)',
                opacity: 0.7,
                textAlign: 'center',
                margin: '0 auto 0.5rem auto',
                width: '100%',
              }}
            >
              Build: {formattedBuildDate}
            </p>

            {/* Check for Updates Button */}
            {'serviceWorker' in navigator && (
              <button
                onClick={updateStatus === 'update-available' ? applyUpdate : checkForUpdates}
                disabled={updateStatus === 'checking' || updateStatus === 'updating'}
                style={{
                  display: 'inline-flex',
                  alignItems: 'center',
                  gap: '0.375rem',
                  padding: '0.375rem 0.75rem',
                  fontSize: '0.8125rem',
                  fontWeight: 500,
                  color:
                    updateStatus === 'up-to-date'
                      ? 'var(--status-qualified)'
                      : updateStatus === 'update-available' || updateStatus === 'updating'
                        ? 'var(--primary)'
                        : 'var(--muted-foreground)',
                  background: 'var(--muted)',
                  border: '1px solid var(--border)',
                  borderRadius: 'var(--token-space-md)',
                  cursor:
                    updateStatus === 'checking' || updateStatus === 'updating' ? 'wait' : 'pointer',
                  transition: 'all 0.2s ease',
                  margin: '0 auto',
                }}
              >
                {updateStatus === 'checking' && (
                  <>
                    <RefreshCw size={14} style={{ animation: 'spin 1s linear infinite' }} />
                    Checking...
                  </>
                )}
                {updateStatus === 'idle' && (
                  <>
                    <RefreshCw size={14} />
                    Check for Updates
                  </>
                )}
                {updateStatus === 'up-to-date' && (
                  <>
                    <CheckCircle size={14} />
                    Up to Date
                  </>
                )}
                {updateStatus === 'update-available' && (
                  <>
                    <RefreshCw size={14} />
                    Tap to Update
                  </>
                )}
                {updateStatus === 'updating' && (
                  <>
                    <Loader2 size={14} style={{ animation: 'spin 1s linear infinite' }} />
                    Updating...
                  </>
                )}
              </button>
            )}
          </div>

          {/* License Key Section */}
          {licenseKey && (
            <div
              style={{
                background: 'var(--muted)',
                padding: '0.75rem',
                borderRadius: 'var(--token-space-md)',
                marginBottom: '1rem',
              }}
            >
              <div
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  gap: 'var(--token-space-sm)',
                  marginBottom: 'var(--token-space-sm)',
                }}
              >
                <Key className="h-4 w-4" style={{ color: 'var(--muted-foreground)' }} />
                <span
                  style={{
                    fontSize: '0.8125rem',
                    fontWeight: 600,
                    color: 'var(--muted-foreground)',
                    textTransform: 'uppercase',
                    letterSpacing: '0.05em',
                  }}
                >
                  License Key
                </span>
              </div>
              <code
                style={{
                  fontSize: '0.75rem',
                  color: 'var(--foreground)',
                  fontFamily: 'monospace',
                  wordBreak: 'break-all',
                  display: 'block',
                }}
              >
                {licenseKey}
              </code>
            </div>
          )}

          {/* Device ID Section - for troubleshooting push notifications */}
          {deviceId && (
            <div
              style={{
                background: 'var(--muted)',
                padding: '0.75rem',
                borderRadius: 'var(--token-space-md)',
                marginBottom: '1rem',
              }}
            >
              <div
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  gap: 'var(--token-space-sm)',
                  marginBottom: 'var(--token-space-sm)',
                }}
              >
                <Smartphone className="h-4 w-4" style={{ color: 'var(--muted-foreground)' }} />
                <span
                  style={{
                    fontSize: '0.8125rem',
                    fontWeight: 600,
                    color: 'var(--muted-foreground)',
                    textTransform: 'uppercase',
                    letterSpacing: '0.05em',
                  }}
                >
                  Device ID
                </span>
                <span
                  style={{
                    fontSize: '0.625rem',
                    color: 'var(--muted-foreground)',
                    opacity: 0.7,
                    marginLeft: 'auto',
                  }}
                >
                  (for support)
                </span>
              </div>
              <code
                style={{
                  fontSize: '0.75rem',
                  color: 'var(--foreground)',
                  fontFamily: 'monospace',
                  wordBreak: 'break-all',
                  display: 'block',
                }}
              >
                {deviceId}
              </code>
            </div>
          )}

          {/* Links Section */}
          <div
            style={{
              display: 'flex',
              flexDirection: 'column',
              gap: 'var(--token-space-md)',
            }}
          >
            <a
              href="https://myk9t.com"
              target="_blank"
              rel="noopener noreferrer"
              style={{
                display: 'flex',
                alignItems: 'center',
                gap: 'var(--token-space-md)',
                padding: 'var(--token-space-md) var(--token-space-lg)',
                background: 'var(--muted)',
                borderRadius: 'var(--token-space-md)',
                color: 'var(--primary)',
                textDecoration: 'none',
                transition: 'all 0.2s ease',
                fontSize: '0.875rem',
                fontWeight: 500,
              }}
              onMouseEnter={e => {
                e.currentTarget.style.background = 'var(--accent)';
                e.currentTarget.style.transform = 'translateY(-2px)';
              }}
              onMouseLeave={e => {
                e.currentTarget.style.background = 'var(--muted)';
                e.currentTarget.style.transform = 'translateY(0)';
              }}
            >
              <Globe className="h-5 w-5" />
              <span>Visit myk9t.com</span>
            </a>
          </div>

          {/* Copyright */}
          <div
            style={{
              marginTop: '1.25rem',
              paddingTop: '0.75rem',
              borderTop: '1px solid var(--border)',
              textAlign: 'center',
            }}
          >
            <p
              style={{
                fontSize: '0.75rem',
                color: 'var(--muted-foreground)',
              }}
            >
              © {new Date().getFullYear()} myK9T. All rights reserved.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};
