/**
 * DogCard — ringside per-entry card primitive.
 *
 * Phase B of the ringside Tailwind migration: styling is now authored as
 * Tailwind utilities directly on the markup (was scoped semantic CSS in
 * `../styles/ringside.css`). Color tokens (`--primary`, `--card`, `--border`,
 * `--muted-foreground`, the `status-*` group) resolve from the host theme; in
 * myK9Show those utilities are generated by the app's Tailwind build (which
 * scans this package's `src`). The armband renders as the accent rounded
 * square; status / result / placement show as a left accent bar via
 * `STATUS_BORDER`. Status pills + result badges still arrive through the
 * `actionButton` / `resultBadges` slots.
 */

import React from 'react';
import { cn } from '@myk9/ui';
import type { DogCardProps } from '../pages/EntryList/pageProps';

/**
 * Left accent bar per status/result/placement (the `statusBorder` prop value).
 * Status colors come from the host's light/dark `status-*` Tailwind group;
 * result/placement use standard palette + medal arbitraries. in-ring is the
 * strongest signal: heavier bar + soft glow + faint gradient (no hard outline).
 */
const STATUS_BORDER: Record<string, string> = {
  'no-status': '',
  'checked-in': 'border-l-[3px] border-l-status-checked-in',
  conflict: 'border-l-[3px] border-l-status-conflict',
  pulled: 'border-l-[3px] border-l-status-pulled',
  'at-gate': 'border-l-[3px] border-l-status-at-gate',
  'come-to-gate': 'border-l-[3px] border-l-status-at-gate',
  'in-ring':
    'border-l-[5px] border-l-status-in-ring shadow-[0_2px_12px_color-mix(in_srgb,var(--status-in-ring)_22%,transparent)] bg-[linear-gradient(to_right,color-mix(in_srgb,var(--status-in-ring)_6%,transparent)_0%,transparent_45%)]',
  scored: 'border-l-[3px] border-l-status-completed',
  'placement-1': 'border-l-[3px] border-l-[#ffd700]',
  'placement-2': 'border-l-[3px] border-l-[#c0c0c0]',
  'placement-3': 'border-l-[3px] border-l-[#cd7f32]',
  'result-qualified': 'border-l-[3px] border-l-status-checked-in',
  'result-nq': 'border-l-[3px] border-l-red-600',
  'result-ex': 'border-l-[3px] border-l-red-600',
  'result-abs': 'border-l-[3px] border-l-violet-600',
  'result-wd': 'border-l-[3px] border-l-violet-600',
};

export const DogCard = React.memo<DogCardProps>(
  ({
    armband,
    callName,
    breed,
    handler,
    onClick,
    className = '',
    statusBorder = 'no-status',
    actionButton,
    resultBadges,
    sectionBadge,
    onPrefetch,
    dragHandle,
  }) => {
    const isLong = String(armband).length >= 4;

    return (
      <div
        className={cn(
          'relative flex min-h-[70px] flex-col overflow-hidden rounded-2xl border border-solid border-border bg-card p-3 shadow-sm transition-[transform,box-shadow,border-color] duration-200',
          onClick &&
            'cursor-pointer hover:-translate-y-0.5 hover:border-primary/30 hover:shadow-lg active:scale-[0.98]',
          STATUS_BORDER[statusBorder] ?? '',
          dragHandle && 'pl-2',
          className
        )}
        onClick={onClick}
        onMouseEnter={onPrefetch}
        onTouchStart={onPrefetch}
        data-testid="dog-card"
      >
        <div className="relative flex items-start gap-3">
          {dragHandle && (
            <div className="-ml-1 flex shrink-0 cursor-grab touch-none items-center justify-center self-center rounded-sm p-0.5 text-muted-foreground active:cursor-grabbing active:text-primary">
              {dragHandle}
            </div>
          )}

          <div className="flex shrink-0 flex-col items-center">
            <div
              className={cn(
                'flex h-14 w-14 min-w-14 items-center justify-center rounded-2xl border-2 border-solid border-white/20 bg-primary font-bold text-primary-foreground shadow-md',
                isLong ? 'text-[0.9375rem]' : 'text-lg'
              )}
              data-testid="dog-card-armband"
            >
              {armband}
            </div>
          </div>

          <div className="min-w-0 flex-1 pr-2">
            <h4 className="mb-1 text-base font-[590] leading-snug tracking-tight text-foreground">
              {callName}
            </h4>
            <p className="mb-0.5 text-sm font-medium text-muted-foreground">{breed}</p>
            <p className="text-xs font-medium text-muted-foreground">{handler}</p>
            {resultBadges && (
              <div className="mt-2 flex flex-wrap items-center gap-2">{resultBadges}</div>
            )}
          </div>
        </div>

        {actionButton && <div className="absolute right-0 top-0 z-10">{actionButton}</div>}

        {sectionBadge && (
          <div
            className={cn(
              'absolute bottom-0 left-0 z-10 flex items-center justify-center rounded-bl-2xl rounded-tr-xl px-3 py-1 text-xs font-semibold text-white',
              sectionBadge.toLowerCase() === 'a' ? 'bg-[#9ca3af]' : 'bg-[#4b5563]'
            )}
            data-testid="section-badge"
          >
            {sectionBadge}
          </div>
        )}
      </div>
    );
  }
);

DogCard.displayName = 'DogCard';

export default DogCard;
