/**
 * DogCard — ringside per-entry card primitive.
 *
 * Phase B of the ringside Tailwind migration: styling is now authored as
 * Tailwind utilities directly on the markup (was scoped semantic CSS in
 * `../styles/ringside.css`). Color tokens (`--primary`, `--card`, `--border`,
 * `--muted-foreground`, the `status-*` group) resolve from the host theme; in
 * myK9Show those utilities are generated by the app's Tailwind build (which
 * scans this package's `src`). The armband renders as the accent rounded
 * square; result / placement show as a left accent bar. Entry lifecycle
 * status arrives through the shared-grammar `actionButton` slot.
 */

import React from 'react';
import { cn } from '@myk9/ui';
import type { DogCardProps } from '../pages/EntryList/pageProps';
import { formatArmband } from '../utils/armband';

/**
 * Left accent bar for result/placement reinforcement (the `statusBorder` prop
 * value). Entry lifecycle status is deliberately absent: the action slot owns
 * its shared icon, label, and color grammar.
 */
const RESULT_BORDER: Record<string, string> = {
  scored: 'border-l-[3px] border-l-status-completed',
  'placement-1': 'border-l-[3px] border-l-[#ffd700]',
  'placement-2': 'border-l-[3px] border-l-[#c0c0c0]',
  'placement-3': 'border-l-[3px] border-l-[#cd7f32]',
  'result-qualified': 'border-l-[3px] border-l-status-checked-in',
  'result-nq': 'border-l-[3px] border-l-red-600',
  'result-ex': 'border-l-[3px] border-l-red-600',
  'result-abs': 'border-l-[3px] border-l-violet-600',
  'result-wd': 'border-l-[3px] border-l-violet-600',
};

export const DogCard = React.memo<DogCardProps>(
  ({
    armband,
    callName,
    breed,
    handler,
    onClick,
    className = '',
    statusBorder = 'no-status',
    primaryAction,
    actionButton,
    favoriteButton,
    resultBadges,
    sectionBadge,
    onPrefetch,
    dragHandle,
    trailing,
    nameAddon,
    variant,
  }) => {
    const isHero = variant === 'hero';
    const armbandText = formatArmband(armband);
    const isLong = armbandText.length >= 4;

    return (
      <div
        className={cn(
          'relative flex min-h-[70px] flex-col overflow-hidden rounded-2xl border border-solid border-border bg-card p-3 shadow-sm transition-[transform,box-shadow,border-color] duration-200',
          onClick &&
            'cursor-pointer hover:-translate-y-0.5 hover:border-primary/30 hover:shadow-lg focus-within:ring-2 focus-within:ring-ring active:scale-[0.98]',
          RESULT_BORDER[statusBorder] ?? '',
          isHero && 'border-primary bg-primary text-primary-foreground',
          variant === 'next' && 'border-2 border-primary',
          dragHandle && 'pl-2',
          className
        )}
        onClick={onClick}
        onMouseEnter={onPrefetch}
        onTouchStart={onPrefetch}
        data-testid="dog-card"
      >
        <div className="relative flex items-center gap-3">
          {dragHandle && (
            <div className="-ml-1 flex shrink-0 cursor-grab touch-none items-center justify-center self-center rounded-sm p-0.5 text-muted-foreground active:cursor-grabbing active:text-primary">
              {dragHandle}
            </div>
          )}

          <div className="flex shrink-0 flex-col items-center">
            <div
              className={cn(
                'flex h-14 w-14 min-w-14 items-center justify-center rounded-2xl border-2 border-solid border-white/20 font-bold shadow-md',
                isHero ? 'bg-white text-primary' : 'bg-primary text-primary-foreground',
                isLong ? 'text-[0.9375rem]' : 'text-lg'
              )}
              data-testid="dog-card-armband"
            >
              {armbandText}
            </div>
          </div>

          <div className={cn('min-w-0 flex-1', favoriteButton && !trailing ? 'pr-12' : 'pr-2')}>
            <h4
              className={cn(
                'mb-1 flex flex-wrap items-center gap-2 font-[590] leading-snug tracking-tight',
                isHero ? 'text-lg text-primary-foreground' : 'text-base text-foreground'
              )}
            >
              {callName}
              {nameAddon}
            </h4>
            <p
              className={cn(
                'mb-0.5 text-sm font-medium',
                isHero ? 'text-primary-foreground/85' : 'text-muted-foreground'
              )}
            >
              {breed}
            </p>
            <p
              className={cn(
                'text-sm font-medium',
                isHero ? 'text-primary-foreground/85' : 'text-muted-foreground'
              )}
            >
              {handler}
            </p>
            {resultBadges && (
              <div className="mt-2 flex flex-wrap items-center gap-2">{resultBadges}</div>
            )}
            {primaryAction && <div className="mt-3 flex items-center">{primaryAction}</div>}
          </div>

          {trailing && (
            <div className="flex min-w-0 max-w-[45%] shrink-0 flex-col items-end gap-1 self-center">
              {trailing}
              {/* With a trailing column the heart joins it, so it never sits on top of the check-in icon. */}
              {favoriteButton}
            </div>
          )}
        </div>

        {actionButton && <div className="absolute right-0 top-0 z-10">{actionButton}</div>}
        {favoriteButton && !trailing && (
          <div className="absolute bottom-2 right-2 z-10">{favoriteButton}</div>
        )}

        {sectionBadge && (
          <div
            className={cn(
              'absolute bottom-0 left-0 z-10 flex items-center justify-center rounded-bl-2xl rounded-tr-xl px-3 py-1 text-xs font-semibold text-white',
              sectionBadge.toLowerCase() === 'a' ? 'bg-[#9ca3af]' : 'bg-[#4b5563]'
            )}
            data-testid="section-badge"
          >
            {sectionBadge}
          </div>
        )}
      </div>
    );
  }
);

DogCard.displayName = 'DogCard';

export default DogCard;
