import { describe, expect, it } from 'vitest';
import { migrateWizardState, WIZARD_STORE_VERSION } from './wizardStore.migrations';

describe('wizard store migration', () => {
  it('converts exact legacy generated labels to derived names', () => {
    const migrated = migrateWizardState(
      {
        trials: [
          {
            id: 'generated',
            name: 'Saturday Trial 2',
            trialDate: '2026-08-01',
            startTimeDraft: '08:00 AM',
          },
          {
            id: 'generated-marker',
            name: 'Summer Classic',
            autoGeneratedName: true,
            trialDate: '2026-08-01',
            startTimeDraft: '10:00 AM',
          },
        ],
      },
      0
    ) as { trials: Array<Record<string, unknown>> };

    expect(migrated.trials).toEqual([
      { id: 'generated', trialDate: '2026-08-01', startTimeDraft: '08:00 AM' },
      { id: 'generated-marker', trialDate: '2026-08-01', startTimeDraft: '10:00 AM' },
    ]);
  });

  it('preserves every non-generated legacy name as an explicit override', () => {
    const migrated = migrateWizardState(
      {
        trials: [
          { id: 'custom', name: 'Novice Scent Work', trialDate: '2026-08-01' },
          { id: 'near-match', name: 'Saturday Trial 2 - Novice', trialDate: '2026-08-01' },
        ],
      },
      0
    ) as { trials: Array<Record<string, unknown>> };

    expect(migrated.trials).toEqual([
      { id: 'custom', trialDate: '2026-08-01', nameOverride: 'Novice Scent Work' },
      {
        id: 'near-match',
        trialDate: '2026-08-01',
        nameOverride: 'Saturday Trial 2 - Novice',
      },
    ]);
  });

  it('leaves drafts at the current version untouched', () => {
    const persisted = { trials: [{ id: 'one', nameOverride: 'Custom' }] };

    expect(migrateWizardState(persisted, WIZARD_STORE_VERSION)).toBe(persisted);
  });
});
