import { describe, expect, it } from 'vitest';
import {
  migrateWizardState,
  recoverInterruptedCloneHydration,
  WIZARD_STORE_VERSION,
} from './wizardStore.migrations';

describe('wizard store migration', () => {
  it('converts exact legacy generated labels to derived names', () => {
    const migrated = migrateWizardState(
      {
        trials: [
          { id: 'generated', name: 'Saturday Trial 2', dateTime: '2026-08-01T08:00:00' },
          {
            id: 'generated-marker',
            name: 'Summer Classic',
            autoGeneratedName: true,
            dateTime: '2026-08-01T10:00:00',
          },
        ],
      },
      0
    ) as { trials: Array<Record<string, unknown>> };

    expect(migrated.trials).toEqual([
      { id: 'generated', dateTime: '2026-08-01T08:00:00' },
      { id: 'generated-marker', dateTime: '2026-08-01T10:00:00' },
    ]);
  });

  it('preserves every non-generated legacy name as an explicit override', () => {
    const migrated = migrateWizardState(
      {
        trials: [
          { id: 'custom', name: 'Novice Scent Work', dateTime: '2026-08-01' },
          { id: 'near-match', name: 'Saturday Trial 2 - Novice', dateTime: '2026-08-01' },
        ],
      },
      0
    ) as { trials: Array<Record<string, unknown>> };

    expect(migrated.trials).toEqual([
      { id: 'custom', dateTime: '2026-08-01', nameOverride: 'Novice Scent Work' },
      {
        id: 'near-match',
        dateTime: '2026-08-01',
        nameOverride: 'Saturday Trial 2 - Novice',
      },
    ]);
  });

  it('leaves drafts at the current version untouched', () => {
    const persisted = { trials: [{ id: 'one', nameOverride: 'Custom' }] };

    expect(migrateWizardState(persisted, WIZARD_STORE_VERSION)).toBe(persisted);
  });

  it('recovers a persisted in-flight clone as retryable after reload', () => {
    expect(
      recoverInterruptedCloneHydration({
        status: 'hydrating',
        sourceShowId: 'source-1',
        sourceShowName: 'Spring Trial',
      })
    ).toEqual({ status: 'failed', sourceShowId: 'source-1', sourceShowName: 'Spring Trial' });
  });

  it('does not preserve an unwakeable hydration state without a source show', () => {
    expect(
      recoverInterruptedCloneHydration({
        status: 'hydrating',
        sourceShowId: null,
        sourceShowName: null,
      })
    ).toEqual({ status: 'idle', sourceShowId: null, sourceShowName: null });
  });
});
