const LEGACY_GENERATED_NAME =
  /^(Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday) Trial [1-9]\d*$/;

export const WIZARD_STORE_VERSION = 1;

/** Convert persisted generated labels to derived defaults and retain custom names as overrides. */
export function migrateWizardState(persistedState: unknown, version: number): unknown {
  if (version >= WIZARD_STORE_VERSION || !persistedState || typeof persistedState !== 'object') {
    return persistedState;
  }

  const state = persistedState as Record<string, unknown>;
  if (!Array.isArray(state.trials)) return state;

  return {
    ...state,
    trials: state.trials.map(value => {
      if (!value || typeof value !== 'object') return value;

      const trial = value as Record<string, unknown>;
      const rest = { ...trial };
      const name = rest.name;
      delete rest.name;
      delete rest.autoGeneratedName;
      const wasGenerated =
        trial.autoGeneratedName === true ||
        (typeof name === 'string' && LEGACY_GENERATED_NAME.test(name));
      const override = wasGenerated
        ? undefined
        : typeof trial.nameOverride === 'string'
          ? trial.nameOverride
          : typeof name === 'string'
            ? name
            : undefined;

      return {
        ...rest,
        ...(override !== undefined ? { nameOverride: override } : {}),
      };
    }),
  };
}
