/** Healthy applied ACL facts from migrations 20260725160000–20260725180000. */
export const anonGrants = (over: Record<string, unknown> = {}) => ({
  tables: [
    ...[
      'achievements',
      'armbands',
      'class_visibility_overrides',
      'classes',
      'clubs',
      'judge_assignments',
      'rule_organizations',
      'rule_sports',
      'rulebooks',
      'rules',
      'show_templates',
      'show_visibility_settings',
      'shows',
      'sport_class_rules',
      'sport_templates',
      'sport_titles',
      'template_fields',
      'trial_visibility_overrides',
      'trials',
      'user_guide',
    ].map(name => ({ name, kind: 'r', privs: 'r' })),
    { name: 'platform_waitlist', kind: 'r', privs: 'a' },
    { name: 'view_public_entry_results', kind: 'v', privs: 'r' },
  ],
  columns: [
    ...['id', 'name', 'call_name', 'breed', 'image_url'].map(column => ({
      name: 'dogs',
      column,
      privs: 'r',
    })),
    ...['id', 'first_name', 'last_name', 'email'].map(column => ({
      name: 'people',
      column,
      privs: 'r',
    })),
    ...[
      'id',
      'class_id',
      'trial_id',
      'show_id',
      'dog_id',
      'armband',
      'handler',
      'run_order',
      'is_in_ring',
      'is_scored',
      'check_in_status',
      'entry_status',
      'jump_height',
      'created_at',
    ].map(column => ({
      name: 'entries',
      column,
      privs: 'r',
    })),
  ],
  defaults: [{ grantor: 'supabase_admin', objtype: 'r', privs: 'arwdDxtm' }],
  ...over,
});
