/**
 * Healthy applied ACL facts from migrations 20260725160000–20260725180000, plus the
 * `classes` column allowlist from 20260730140000 (MYK9-116), plus the public judge-assignment
 * columns from MYK9-146. Column-scoped tables appear ONLY in `columns` — their table-level
 * SELECT was revoked so private columns remain withheld.
 */
export const anonGrants = (over: Record<string, unknown> = {}) => ({
  tables: [
    ...[
      'achievements',
      'armbands',
      'class_visibility_overrides',
      'clubs',
      'rule_organizations',
      'rule_sports',
      'rulebooks',
      'rules',
      'show_templates',
      'show_visibility_settings',
      'shows',
      'sport_class_rules',
      'sport_templates',
      'sport_titles',
      'trial_visibility_overrides',
      'trials',
      'user_guide',
    ].map(name => ({ name, kind: 'r', privs: 'r' })),
    { name: 'platform_waitlist', kind: 'r', privs: 'a' },
    { name: 'view_public_entry_results', kind: 'v', privs: 'r' },
  ],
  columns: [
    // Restated rather than imported from ANON_COLUMN_ALLOWLIST: a fixture that derives
    // from the thing it validates cannot catch an edit to that list. num_hides, has_blank
    // and hides_known are absent on purpose.
    ...[
      'id',
      'trial_id',
      'name',
      'description',
      'level',
      'element',
      'section',
      'competition_type',
      'entry_fee',
      'max_entries',
      'allow_waitlist',
      'max_dogs_per_handler',
      'breed_restrictions',
      'jump_heights',
      'age_min',
      'age_max',
      'height_min',
      'height_max',
      'handler_age_min',
      'handler_age_max',
      'start_time',
      'estimated_duration',
      'actual_start_time',
      'actual_end_time',
      'status',
      'time_limit_seconds',
      'num_areas',
      'max_faults',
      'qualifying_threshold',
      'is_scoring_finalized',
      'results_released_at',
      'dogs_ahead_notification_count',
      'total_entries_count',
      'checked_in_count',
      'scored_count',
      'created_at',
      'updated_at',
      'deleted_at',
      'deleted_by',
      'class_number',
      'timer_mode',
      'distraction_count',
      'is_results_reviewed',
      'judge_name',
      'time_limit_area2_seconds',
      'time_limit_area3_seconds',
      'display_order',
      'results_released_by',
      'version',
      'status_source',
      'reopened_after_closeout_at',
      'revised_expected_start',
    ].map(column => ({
      name: 'classes',
      column,
      privs: 'r',
    })),
    ...['id', 'name', 'call_name', 'breed', 'image_url'].map(column => ({
      name: 'dogs',
      column,
      privs: 'r',
    })),
    ...['id', 'first_name', 'last_name', 'email'].map(column => ({
      name: 'people',
      column,
      privs: 'r',
    })),
    ...[
      'id',
      'class_id',
      'trial_id',
      'show_id',
      'dog_id',
      'armband',
      'handler',
      'run_order',
      'is_in_ring',
      'is_scored',
      'check_in_status',
      'entry_status',
      'jump_height',
      'created_at',
      'deleted_at',
    ].map(column => ({
      name: 'entries',
      column,
      privs: 'r',
    })),
    ...[
      'id',
      'person_id',
      'show_id',
      'trial_id',
      'class_id',
      'status',
      'invited_at',
      'confirmed_at',
      'created_at',
      'updated_at',
    ].map(column => ({
      name: 'judge_assignments',
      column,
      privs: 'r',
    })),
  ],
  defaults: [{ grantor: 'supabase_admin', objtype: 'r', privs: 'arwdDxtm' }],
  ...over,
});
