import type { PerformanceData, DogPerformance } from './AnalyticsDashboard.types';

export const mockPerformanceData: PerformanceData[] = [
  {
    month: 'Jan',
    shows: 4,
    placements: 7,
    earnings: 2400,
    expenses: 1800,
    firstPlace: 2,
    secondPlace: 3,
    thirdPlace: 2,
  },
  {
    month: 'Feb',
    shows: 6,
    placements: 9,
    earnings: 3200,
    expenses: 2200,
    firstPlace: 3,
    secondPlace: 4,
    thirdPlace: 2,
  },
  {
    month: 'Mar',
    shows: 8,
    placements: 12,
    earnings: 4100,
    expenses: 2800,
    firstPlace: 4,
    secondPlace: 5,
    thirdPlace: 3,
  },
  {
    month: 'Apr',
    shows: 5,
    placements: 8,
    earnings: 2800,
    expenses: 2000,
    firstPlace: 2,
    secondPlace: 4,
    thirdPlace: 2,
  },
  {
    month: 'May',
    shows: 7,
    placements: 11,
    earnings: 3600,
    expenses: 2500,
    firstPlace: 3,
    secondPlace: 5,
    thirdPlace: 3,
  },
  {
    month: 'Jun',
    shows: 9,
    placements: 14,
    earnings: 4800,
    expenses: 3200,
    firstPlace: 5,
    secondPlace: 6,
    thirdPlace: 3,
  },
];

export const mockDogPerformance: DogPerformance[] = [
  {
    id: '1',
    name: 'Champion Rex',
    breed: 'German Shepherd',
    shows: 15,
    wins: 8,
    winRate: 53.3,
    earnings: 4200,
    lastShow: new Date('2024-06-15'),
  },
  {
    id: '2',
    name: 'Lady Belle',
    breed: 'Golden Retriever',
    shows: 12,
    wins: 6,
    winRate: 50.0,
    earnings: 3200,
    lastShow: new Date('2024-06-10'),
  },
  {
    id: '3',
    name: 'Duke Thunder',
    breed: 'Rottweiler',
    shows: 18,
    wins: 12,
    winRate: 66.7,
    earnings: 5800,
    lastShow: new Date('2024-06-20'),
  },
  {
    id: '4',
    name: 'Princess Luna',
    breed: 'Border Collie',
    shows: 10,
    wins: 4,
    winRate: 40.0,
    earnings: 2100,
    lastShow: new Date('2024-06-05'),
  },
];

export const placementData = [
  { name: '1st Place', value: 19, color: '#ffd700' },
  { name: '2nd Place', value: 27, color: '#c0c0c0' },
  { name: '3rd Place', value: 15, color: '#cd7f32' },
  { name: 'Other', value: 8, color: '#94a3b8' },
];
